### ISSUE TITLE
inconsistent behavior related to robot paths

### ISSUE THREAD

**Issue by dominikborkowski** [easybuilders/easybuild#101]
Hello,

In my attempt to create a set of easyconfigs customized to my site, that would override the ones provided with easybuild, I have discovered a few inconsistencies in how easybuild behaves. Below are some simple examples, and I'd be happy to provide more details. (this is on easybuild 2.0.0)

case #1: attempting to implement custom OpenMPI-1.8.4-GCC-4.8.4.eb, which builds against InfiniPath-PSM rather than openibverbs. The file is placed in /apps/easybuild/ebfiles_repo-vbi/generic/OpenMPI/OpenMPI-1.8.4-GCC-4.8.4.eb and EASYBUILD_MODULE_NAMING_SCHEME=HierarchicalMNS is set.

dom@sfxlogin3:~> echo $EASYBUILD_ROBOT
/apps/easybuild/ebfiles_repo-vbi/generic:/apps/easybuild/ebfiles_repo-vbi/shadowfax-sandy_bridge:/apps/easybuild/ebfiles_repo/shadowfax-sandy_bridge

/apps/easybuild/ebfiles_repo-vbi/generic:/apps/easybuild/ebfiles_repo-vbi/shadowfax-sandy_bridge:/apps/easybuild/ebfiles_repo/shadowfax-sandy_bridge
dom@sfxlogin3:~> eb -S OpenMPI-1.8.4-GCC-4.8.4.eb
== temporary log file in case of crash /tmp/eb-j7eVPd/easybuild-AkNcq4.log
== Searching (case-insensitive) for 'OpenMPI-1.8.4-GCC-4.8.4.eb' in /apps/easybuild/ebfiles_repo-vbi/generic
== Searching (case-insensitive) for 'openmpi-1.8.4-gcc-4.8.4.eb' in /apps/easybuild/ebfiles_repo-vbi/shadowfax-sandy_bridge
== Searching (case-insensitive) for 'openmpi-1.8.4-gcc-4.8.4.eb' in /apps/easybuild/ebfiles_repo/shadowfax-sandy_bridge
== Searching (case-insensitive) for 'openmpi-1.8.4-gcc-4.8.4.eb' in /apps/easybuild/software/shadowfax-sandy_bridge/Core/EasyBuild/2.0.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.0.0-py2.6.egg/easybuild/easyconfigs
CFGS1=/apps/easybuild/ebfiles_repo-vbi/generic/OpenMPI
CFGS2=/apps/easybuild/ebfiles_repo/shadowfax-sandy_bridge/OpenMPI
CFGS3=/apps/easybuild/software/shadowfax-sandy_bridge/Core/EasyBuild/2.0.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.0.0-py2.6.egg/easybuild/easyconfigs/o/OpenMPI
- $CFGS1/OpenMPI-1.8.4-GCC-4.8.4.eb
- $CFGS2/OpenMPI-1.8.4-GCC-4.8.4.eb
- $CFGS2/OpenMPI-1.8.4-GCC-4.8.4.eb.backup
- $CFGS3/OpenMPI-1.8.4-GCC-4.8.4.eb
  == temporary log file /tmp/eb-j7eVPd/easybuild-AkNcq4.log has been removed.
  == temporary directory /tmp/eb-j7eVPd has been removed.

We see that the file I'm interested in shows up under CFGS1. 

Now, when trying to build it with dry-run, we do not see that location listed anymore:

dom@sfxlogin3:~> eb OpenMPI-1.8.4-GCC-4.8.4.eb -Dr
== temporary log file in case of crash /tmp/eb-xTHykI/easybuild-CiI3qE.log
Dry run: printing build status of easyconfigs and dependencies
CFGS=/apps/easybuild/software/shadowfax-sandy_bridge/Core/EasyBuild/2.0.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.0.0-py2.6.egg/easybuild/easyconfigs
- [x] $CFGS/g/GCC/GCC-4.8.4.eb (module: Core | GCC/4.8.4)
- [x] $CFGS/m/M4/M4-1.4.17-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | M4/1.4.17)
- [x] $CFGS/l/libtool/libtool-2.4.5-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | libtool/2.4.5)
- [x] $CFGS/a/Autoconf/Autoconf-2.69-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | Autoconf/2.69)
- [x] $CFGS/a/Automake/Automake-1.15-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | Automake/1.15)
- [x] $CFGS/n/numactl/numactl-2.0.10-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | numactl/2.0.10)
- [x] $CFGS/h/hwloc/hwloc-1.10.1-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | hwloc/1.10.1)
- [x] $CFGS/o/OpenMPI/OpenMPI-1.8.4-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | OpenMPI/1.8.4)
  == temporary log file /tmp/eb-xTHykI/easybuild-CiI3qE.log has been removed.
  == temporary directory /tmp/eb-xTHykI has been removed.

Trying to build it without dry-run, actually shows it trying to pull from the custom location:

dom@sfxlogin3:~> eb OpenMPI-1.8.4-GCC-4.8.4.eb -f
== temporary log file in case of crash /tmp/eb-ouQ1vx/easybuild-FIWOJA.log
== resolving dependencies ...
== processing EasyBuild easyconfig /apps/easybuild/ebfiles_repo-vbi/generic/OpenMPI/OpenMPI-1.8.4-GCC-4.8.4.eb
== building and installing Compiler/GCC/4.8.4/OpenMPI/1.8.4...
== fetching files...

Trying now the same thing but with --robot option enabled, shows trying to pull from a different location, despite all dependencies already met:

dom@sfxlogin3:~> eb OpenMPI-1.8.4-GCC-4.8.4.eb -f --robot
== temporary log file in case of crash /tmp/eb-0GBzsY/easybuild-PGVw_H.log
== resolving dependencies ...
== processing EasyBuild easyconfig /apps/easybuild/software/shadowfax-sandy_bridge/Core/EasyBuild/2.0.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.0.0-py2.6.egg/easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-GCC-4.8.4.eb
== building and installing Compiler/GCC/4.8.4/OpenMPI/1.8.4...
== fetching files...

---

Case #2, Trying to do the same with another package: Python-2.7.9-foss-2015a.eb, file is available as /apps/easybuild/ebfiles_repo-vbi/generic/Python/Python-2.7.9-foss-2015a.eb

Search finds it in both custom and system locations, with custom location specified as the first one:

dom@sfxlogin3:~> eb -S Python-2.7.9-foss-2015a.eb
== temporary log file in case of crash /tmp/eb-aYayGF/easybuild-eFhRtK.log
== Searching (case-insensitive) for 'Python-2.7.9-foss-2015a.eb' in /apps/easybuild/ebfiles_repo-vbi/generic
== Searching (case-insensitive) for 'python-2.7.9-foss-2015a.eb' in /apps/easybuild/ebfiles_repo-vbi/shadowfax-sandy_bridge
== Searching (case-insensitive) for 'python-2.7.9-foss-2015a.eb' in /apps/easybuild/ebfiles_repo/shadowfax-sandy_bridge
== Searching (case-insensitive) for 'python-2.7.9-foss-2015a.eb' in /apps/easybuild/software/shadowfax-sandy_bridge/Core/EasyBuild/2.0.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.0.0-py2.6.egg/easybuild/easyconfigs
CFGS1=/apps/easybuild/ebfiles_repo-vbi/generic/Python
CFGS2=/apps/easybuild/software/shadowfax-sandy_bridge/Core/EasyBuild/2.0.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.0.0-py2.6.egg/easybuild/easyconfigs/p/Python
- $CFGS1/Python-2.7.9-foss-2015a.eb
- $CFGS2/Python-2.7.9-foss-2015a.eb
  == temporary log file /tmp/eb-aYayGF/easybuild-eFhRtK.log has been removed.
  == temporary directory /tmp/eb-aYayGF has been removed.

Dry run shows only the system location:

dom@sfxlogin3:~> eb Python-2.7.9-foss-2015a.eb -Dr
== temporary log file in case of crash /tmp/eb-nionjg/easybuild-frIi_i.log
Dry run: printing build status of easyconfigs and dependencies
CFGS=/apps/easybuild/software/shadowfax-sandy_bridge/Core/EasyBuild/2.0.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.0.0-py2.6.egg/easybuild/easyconfigs
- [x] $CFGS/g/GCC/GCC-4.9.2.eb (module: Core | GCC/4.9.2)
- [x] $CFGS/o/OpenBLAS/OpenBLAS-0.2.13-GCC-4.9.2-LAPACK-3.5.0.eb (module: Compiler/GCC/4.9.2 | OpenBLAS/0.2.13-LAPACK-3.5.0)
- [x] $CFGS/l/libtool/libtool-2.4.2-GCC-4.9.2.eb (module: Compiler/GCC/4.9.2 | libtool/2.4.2)
- [x] $CFGS/m/M4/M4-1.4.17-GCC-4.9.2.eb (module: Compiler/GCC/4.9.2 | M4/1.4.17)
- [x] $CFGS/a/Autoconf/Autoconf-2.69-GCC-4.9.2.eb (module: Compiler/GCC/4.9.2 | Autoconf/2.69)
- [x] $CFGS/a/Automake/Automake-1.15-GCC-4.9.2.eb (module: Compiler/GCC/4.9.2 | Automake/1.15)
- [x] $CFGS/n/numactl/numactl-2.0.10-GCC-4.9.2.eb (module: Compiler/GCC/4.9.2 | numactl/2.0.10)
- [x] $CFGS/h/hwloc/hwloc-1.10.0-GCC-4.9.2.eb (module: Compiler/GCC/4.9.2 | hwloc/1.10.0)
- [x] $CFGS/o/OpenMPI/OpenMPI-1.8.4-GCC-4.9.2.eb (module: Compiler/GCC/4.9.2 | OpenMPI/1.8.4)
- [x] $CFGS/g/gompi/gompi-2015a.eb (module: Core | gompi/2015a)
- [x] $CFGS/f/FFTW/FFTW-3.3.4-gompi-2015a.eb (module: MPI/GCC/4.9.2/OpenMPI/1.8.4 | FFTW/3.3.4)
- [x] $CFGS/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2015a-OpenBLAS-0.2.13-LAPACK-3.5.0.eb (module: MPI/GCC/4.9.2/OpenMPI/1.8.4 | ScaLAPACK/2.0.2-OpenBLAS-0.2.13-LAPACK-3.5.0)
- [x] $CFGS/f/foss/foss-2015a.eb (module: Core | foss/2015a)
- [x] $CFGS/n/ncurses/ncurses-5.9-foss-2015a.eb (module: MPI/GCC/4.9.2/OpenMPI/1.8.4 | ncurses/5.9)
- [x] $CFGS/b/bzip2/bzip2-1.0.6-foss-2015a.eb (module: MPI/GCC/4.9.2/OpenMPI/1.8.4 | bzip2/1.0.6)
- [x] $CFGS/z/zlib/zlib-1.2.8-foss-2015a.eb (module: MPI/GCC/4.9.2/OpenMPI/1.8.4 | zlib/1.2.8)
- [x] $CFGS/l/libreadline/libreadline-6.3-foss-2015a.eb (module: MPI/GCC/4.9.2/OpenMPI/1.8.4 | libreadline/6.3)
- [ ] $CFGS/p/Python/Python-2.7.9-foss-2015a.eb (module: MPI/GCC/4.9.2/OpenMPI/1.8.4 | Python/2.7.9)
  == temporary log file /tmp/eb-nionjg/easybuild-frIi_i.log has been removed.
  == temporary directory /tmp/eb-nionjg has been removed.
  dom@sfxlogin3:~>

**Comment by dominikborkowski** [comment]
Oops, hit enter before finishing:

Trying to set the EASYBUILD_ROBOT_PATH to the same values as EASYBUILD_ROBOT:
dom@sfxlogin3:~> echo $EASYBUILD_ROBOT_PATH

dom@sfxlogin3:~> export EASYBUILD_ROBOT_PATH=$EASYBUILD_ROBOT

Same experience as before. Running with --robot pulls from the system location, rather then the custom one:

dom@sfxlogin3:~> eb -S OpenMPI-1.8.4-GCC-4.8.4.eb
== temporary log file in case of crash /tmp/eb-0FkDE3/easybuild-NAJkgn.log
== Searching (case-insensitive) for 'OpenMPI-1.8.4-GCC-4.8.4.eb' in /apps/easybuild/ebfiles_repo-vbi/generic
== Searching (case-insensitive) for 'openmpi-1.8.4-gcc-4.8.4.eb' in /apps/easybuild/ebfiles_repo-vbi/shadowfax-sandy_bridge
== Searching (case-insensitive) for 'openmpi-1.8.4-gcc-4.8.4.eb' in /apps/easybuild/ebfiles_repo/shadowfax-sandy_bridge
== Searching (case-insensitive) for 'openmpi-1.8.4-gcc-4.8.4.eb' in /apps/easybuild/software/shadowfax-sandy_bridge/Core/EasyBuild/2.0.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.0.0-py2.6.egg/easybuild/easyconfigs
CFGS1=/apps/easybuild/ebfiles_repo-vbi/generic/OpenMPI
CFGS2=/apps/easybuild/ebfiles_repo/shadowfax-sandy_bridge/OpenMPI
CFGS3=/apps/easybuild/software/shadowfax-sandy_bridge/Core/EasyBuild/2.0.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.0.0-py2.6.egg/easybuild/easyconfigs/o/OpenMPI
 * $CFGS1/OpenMPI-1.8.4-GCC-4.8.4.eb
 * $CFGS2/OpenMPI-1.8.4-GCC-4.8.4.eb
 * $CFGS2/OpenMPI-1.8.4-GCC-4.8.4.eb.backup
 * $CFGS3/OpenMPI-1.8.4-GCC-4.8.4.eb
== temporary log file /tmp/eb-0FkDE3/easybuild-NAJkgn.log has been removed.
== temporary directory /tmp/eb-0FkDE3 has been removed.

dom@sfxlogin3:~> eb OpenMPI-1.8.4-GCC-4.8.4.eb -f -Dr
== temporary log file in case of crash /tmp/eb-G7d0IN/easybuild-5w3u24.log
Dry run: printing build status of easyconfigs and dependencies
CFGS=/apps/easybuild/software/shadowfax-sandy_bridge/Core/EasyBuild/2.0.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.0.0-py2.6.egg/easybuild/easyconfigs
 * [x] $CFGS/g/GCC/GCC-4.8.4.eb (module: Core | GCC/4.8.4)
 * [x] $CFGS/m/M4/M4-1.4.17-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | M4/1.4.17)
 * [x] $CFGS/l/libtool/libtool-2.4.5-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | libtool/2.4.5)
 * [x] $CFGS/a/Autoconf/Autoconf-2.69-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | Autoconf/2.69)
 * [x] $CFGS/a/Automake/Automake-1.15-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | Automake/1.15)
 * [x] $CFGS/n/numactl/numactl-2.0.10-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | numactl/2.0.10)
 * [x] $CFGS/h/hwloc/hwloc-1.10.1-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | hwloc/1.10.1)
 * [F] $CFGS/o/OpenMPI/OpenMPI-1.8.4-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | OpenMPI/1.8.4)
== temporary log file /tmp/eb-G7d0IN/easybuild-5w3u24.log has been removed.
== temporary directory /tmp/eb-G7d0IN has been removed.

dom@sfxlogin3:~> eb OpenMPI-1.8.4-GCC-4.8.4.eb -f --robot -Dr
== temporary log file in case of crash /tmp/eb-GNocpf/easybuild-_iAiR_.log
Dry run: printing build status of easyconfigs and dependencies
CFGS=/apps/easybuild/software/shadowfax-sandy_bridge/Core/EasyBuild/2.0.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.0.0-py2.6.egg/easybuild/easyconfigs
 * [x] $CFGS/g/GCC/GCC-4.8.4.eb (module: Core | GCC/4.8.4)
 * [x] $CFGS/m/M4/M4-1.4.17-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | M4/1.4.17)
 * [x] $CFGS/l/libtool/libtool-2.4.5-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | libtool/2.4.5)
 * [x] $CFGS/a/Autoconf/Autoconf-2.69-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | Autoconf/2.69)
 * [x] $CFGS/a/Automake/Automake-1.15-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | Automake/1.15)
 * [x] $CFGS/n/numactl/numactl-2.0.10-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | numactl/2.0.10)
 * [x] $CFGS/h/hwloc/hwloc-1.10.1-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | hwloc/1.10.1)
 * [F] $CFGS/o/OpenMPI/OpenMPI-1.8.4-GCC-4.8.4.eb (module: Compiler/GCC/4.8.4 | OpenMPI/1.8.4)
== temporary log file /tmp/eb-GNocpf/easybuild-_iAiR_.log has been removed.
== temporary directory /tmp/eb-GNocpf has been removed.

dom@sfxlogin3:~> eb OpenMPI-1.8.4-GCC-4.8.4.eb -f
== temporary log file in case of crash /tmp/eb-IZWHqm/easybuild-tGAXZo.log
== resolving dependencies ...
== processing EasyBuild easyconfig /apps/easybuild/ebfiles_repo-vbi/generic/OpenMPI/OpenMPI-1.8.4-GCC-4.8.4.eb
== building and installing Compiler/GCC/4.8.4/OpenMPI/1.8.4...
== fetching files...
== creating build dir, resetting environment...

dom@sfxlogin3:~> eb OpenMPI-1.8.4-GCC-4.8.4.eb -f --robot
== temporary log file in case of crash /tmp/eb-WsGCMT/easybuild-CH2TT2.log
== resolving dependencies ...
== processing EasyBuild easyconfig /apps/easybuild/software/shadowfax-sandy_bridge/Core/EasyBuild/2.0.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.0.0-py2.6.egg/easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-GCC-4.8.4.eb
== building and installing Compiler/GCC/4.8.4/OpenMPI/1.8.4...
== fetching files...
== creating build dir, resetting environment...
== unpacking...

Any hints as to why:

1) dry run is not showing all (and correct) locations it's going to pull from
2) why do EASYBUILD_ROBOT and EASYBUILD_ROBOT_PATH do not allow for overriding the easyconfig when --robot option is specified?

Thanks!

**Comment by boegel** [comment]
I think this explains what you're seeing:

* command line options override matching `$EASYBUILD_X` environment variables; so, using `--robot` or `-r` renders your `$EASYBUILD_ROBOT` value unused; you should really be using `--robot-paths` instead to expand the search path for the robot, `--robot` is only intended for cmdline usage (to enable dependency resolution, and perhaps also specify a temporary location where easyconfigs should be picked up)

* for `--robot-paths`, the correct corresponding environment variable is `$EASYBUILD_ROBOT_PATHS`, not `...PATH`; the latter is simply ignored. Maybe we should make EB complain if it finds non-sensible `$EASYBUILD_X` environment variables being defined? Would that help?

**Comment by dominikborkowski** [comment]
Yikes, indeed, I should have been trying EASYBUILD_ROBOT_PATHS instead of EASYBUILD_ROBOT_PATH. Thank you. While I see why it matches the --robot-paths option, it's also easy to miss as it doesn't follow the convention used for all other EASYBUILD_*_PATH. 

Question remains though: why does dry run show only a single location, while the actual build can pick easyconfig from another, not necessarily the same? 
 
Now, by copying populating EASYBUILD_ROBOT_PATHS with the custom paths, I notice this will cause another issue for me: the default location is now no longer available. Considering I'm using environment variables to preset the easybuild configuration, rather than a configuration file, that poses a peculiar issue: I no longer can access the default easyconfigs. I could hardcode and prepend a path for the easybuild location, but at that point I'm not sure which version will be loading. Is there a way around it without resorting to using a configuration file?

**Comment by boegel** [comment]
The 'short' dry run `-D` will try to collapse the common prefix via `$CFGS`, the 'long' `--dry-run` will not collapse.
When you combining dry-run with robot, you're overwriting `$EASYBUILD_ROBOT`, and hence dry-run is only seeing the system location. Does that explain what you've been seeing?

The path to the default easyconfigs is indeed only available in configuration files (something I'm not very happy with). I'm not sure what we can do here... Any suggestions? Since the shell will expand variables before `eb` can parse the values, we can't just define `$EASYBUILD_ DEFAULT_ROBOT_PATHS` in `eb` itself, that's too late...

How would you define `$EASYBUILD_ROBOT_PATHS` to specify that it should also include the path to the default easyconfigs?

**Comment by dominikborkowski** [comment]
Thank you, seems now everything makes more sense, and ultimately answers the question as to why I was seeing this problem: enabling dependency solving by specifying --robot was resulting in omitting paths specified in the environment variable. 

Considering that for my purpose using EASYBUILD_ROBOT_PATHS is not an option, as this prevents access to the easyconfigs provided by easybuild, I need to rethink my strategy. Ultimately, the solutions that could work for me would be either:

1) decoupling dependency resolution from EASYBUILD_ROBOT. I'm still not sure why they are tied together. By itself, setting EASYBUILD_ROBOT variable provides me with the ability to override easyconfigs provided by easybuild. 

2) ability to prepend (and append) items to the path where easybuild would search for easyconfigs (both for individual builds and when it needs to pull them for dependency resolution). Perhaps by having additional environment modules/config options? 

The second solution could potentially provide a clean way to have custom easyconfigs for both overriding what easybuild provides, and adding ones that are not present. Not to mention, it would provide easy way of having a logical segregation between easyconfigs generated by easybuild and placed in the EASYBUILD_REPOSITORYPATH from ones maintained manually.

**Comment by boegel** [comment]
option 2) could be supported when https://github.com/hpcugent/vsc-base/issues/161 is resolved, @stdweird is going to look into that

**Comment by boegel** [comment]
documentation update via https://github.com/hpcugent/easybuild/pull/102

**Comment by boegel** [comment]
PR to add support for prepending/appending to robot search path via  `--robot-paths` and `$EASYBUILD_ROBOT_PATHS`: https://github.com/hpcugent/easybuild-framework/pull/1252/

**Comment by boegel** [comment]
@dominikborkowski: hpcugent/easybuild-framework#1252 is merged, which adds support for prepend/appending to `--robot-paths` (via cmdline, env var and cfgfile); this will be included in the upcoming EasyBuild v2.1. Documentation update for this will follow.

I think this issue can closed once that's tackled?

**Comment by dominikborkowski** [comment]
Sounds great! Thank you, and yes.

**Comment by migueldiascosta** [comment]
the documentation was updated (https://easybuild.readthedocs.io/en/latest/Using_the_EasyBuild_command_line.html#controlling-the-robot-search-path) but the issue wasn't closed, closing now
