### ISSUE TITLE
Replace toolkit with toolchain everywhere

### ISSUE THREAD

**Issue by fgeorgatos** [easybuilders/easybuild#11]
Especially in the location below, a sed 's/toolkit/toolchain/g' would not hurt much!

https://github.com/hpcugent/easybuild/wiki/Using-EasyBuild#wiki-software-build-options

**Comment by migueldiascosta** [comment]
I'd say this was done, e.g. https://easybuild.readthedocs.io/en/latest/search.html?q=toolkit&check_keywords=yes&area=default :)
