### ISSUE TITLE
Support for user-specific paths

### ISSUE THREAD

**Issue by dominikborkowski** [easybuilders/easybuild#112]
Per comments in https://github.com/hpcugent/easybuild/issues/106, I'd like to request ability to set user-specific paths. Namely the EASYBUILD_BUILDPATH and corresponding 'buildpath' configuration option. 

Here's how we are able to accomplish it via the environment module:

setenv EASYBUILD_BUILDPATH /dev/shm/$::env(USER)/build

Thanks!

**Comment by migueldiascosta** [comment]
let's follow up on this at https://github.com/easybuilders/easybuild-framework/issues/3134
