### ISSUE TITLE
integrate API documentation into easybuild.readthedocs.org

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild#131]
API docs are now hidden on Jenkins, see https://jenkins1.ugent.be/view/EasyBuild/job/easybuild-framework_unit-test_hpcugent_master/Documentation/

These page are generated straight from the code using epydoc (http://epydoc.sourceforge.net/), using `epydoc easybuild`

TODO:
- see whether epydoc can generate the API docs in `.rst` (or .md, if .rst doesn't work) format, to easily integrate them into easybuild.readthedocs.org (I suspect it would
- if so, try it (and create a script for it)
- if not, see if there are alternatives

**Comment by boegel** [comment]
@Caylo: can you take a look at this?

**Comment by boegel** [comment]
@Caylo: you can push to my `api` branch to update http://boegel-eb.readthedocs.org/en/api/api.html

**Comment by Caylo** [comment]
Used sphinx, see https://github.com/hpcugent/easybuild/pull/139

**Comment by migueldiascosta** [comment]
this has been done (https://easybuild.readthedocs.io/en/latest/api/easybuild.html), but the issue was left open, closing
