### ISSUE TITLE
Make Jenkins less verbose in sending notifications upon unit tests

### ISSUE THREAD

**Issue by fgeorgatos** [easybuilders/easybuild#22]
Hi,

looking at the following jenkins report
https://jenkins1.ugent.be/job/easybuild-easyconfigs-pr-builder/379/console
I was able to infer that jenkins somehow looks at (a subset of) past commits, part of
`/Users/fotis/uni.lu/easybuild-easyconfigs]$ git log|grep Author:|cut -d: -f2|sort -u`,
and sends notifications to that subset.

I have not understood the conditions and exact specs but it is obvious that fi.
`wjurkowski@node-59.gaia-cluster.uni.lux` should not be notified for all the other bits that don't relate to gromacs or gatk. My impression is, Jenkins current config makes it a bit too verbose. I can handle that, but others may be not and people have been wondering.

**Comment by migueldiascosta** [comment]
assuming this is no longer relevant, even at UGent
