### ISSUE TITLE
compiling GAMESS-US-20140512-R1 error

### ISSUE THREAD

**Issue by eediaz1987** [easybuilders/easybuild#232]
I am compiling to install with easybuild GAMESS-US-20140512-R1-goolf-1.7.20.eb, i created the easyconfig, and i have this error

ERROR: Build of /home/oau/.local/easybuild/software/EasyBuild/2.6.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.6.0-py2.7.egg/easybuild/easyconfigs/g/GAMESS-US/GAMESS-US-20141205-R1-goolf-1.7.20.eb failed (err: "build failed (first 300 chars): run_cmd_qa: cmd  ./config  : Max nohits 50 reached: end of output k for Pathscale's compiler.\nPlease enter your choice of FORTRAN:  \ngfortran is very robust, so this is a wise choice.\n \nPlease type 'gfortran -dumpversion' or else 'gfortran -v' to\ndetect the version number of your gfortran.\nThis repl")

here i atach the easyconfig
[GAMESS-US-20141205-R1-goolf-1.7.20.txt](https://github.com/hpcugent/easybuild/files/328349/GAMESS-US-20141205-R1-goolf-1.7.20.txt)

**Comment by boegel** [comment]
@eediaz1987 sorry for not replying to this... did you get this problem fixed?

If running an interactive command takes a while with no output, EasyBuild assumes a question is being asked that it doesn't no an answer to, and it bails.

It's unclear to me whether this is actually the case here...

Does this occur every time you try to install GAMESS-US? Also when you to a test install to a fast location (e.g. `/dev/shm`)?

**Comment by eediaz1987** [comment]
I have GAMESS-US installed from source without EasyBuild, but i try to
install using EasyBuild and get that error

2016-07-13 12:45 GMT-04:00 Kenneth Hoste <notifications@github.com>:

**Comment by boegel** [comment]
@eediaz1987 this problem probably occurs because you're installing GAMESS-US to a (very) slow filesystem...

Can you try installing it to a different location (e.g. a local filesystem or even `/dev/shm/`) to verify that this is indeed the case?

**Comment by eediaz1987** [comment]
ok, thanks, now i have the hpc of the universidad de oriente shutdown,
because the vacations, i restart my work in september, i am go to try
installing it to a diferent location, and send you the results

2016-08-19 9:14 GMT-04:00, Kenneth Hoste <notifications@github.com>:

**Comment by boegel** [comment]
@eediaz1987 any updates on this? We briefly talked about it yesterday...

**Comment by eediaz1987** [comment]
i will try to do the installation as you teach me yesterday, but i have to
do it when i arrived to Cuba

2016-11-10 21:57 GMT+11:00 Kenneth Hoste <notifications@github.com>:

**Comment by boegel** [comment]
@eediaz1987 ping on this?
