### ISSUE TITLE
Intel itac 8.1.4.045 does not install with EB 1.11.0

### ISSUE THREAD

**Issue by garvct** [easybuilders/easybuild#27]
The current itac easyblock does not use the new Intel licensing scheme defined in intelbase.

I modified itac.py easyblock to use the new licensing scheme and allow installation of itac 8.1.4.045.

import os

from easybuild.framework.easyconfig import CUSTOM
from distutils.version import LooseVersion
from easybuild.easyblocks.generic.intelbase import IntelBase, ACTIVATION_NAME_2012, LICENSE_FILE_NAME_2012, ACTIVATION_NAME, LICENSE_FILE_NAME

class EB_itac(IntelBase):
    """
    Class that can be used to install itac
    - tested with Intel Trace Analyzer and Collector 7.2.1.008
    """

```
@staticmethod
def extra_options():
    extra_vars = [('preferredmpi', ['impi3', "Preferred MPI type (default: 'impi3')", CUSTOM])]
    return IntelBase.extra_options(extra_vars)

def install_step(self):
    """
    Actual installation
    - create silent cfg file
    - execute command
    """

    silent_cfg_names_map = None

    if LooseVersion(self.version) < LooseVersion('8.1'):
        silent_cfg_names_map = {
            'activation_name': ACTIVATION_NAME_2012,
            'license_file_name': LICENSE_FILE_NAME_2012,
        }
    else:
        silent_cfg_names_map = {
            'activation_name': ACTIVATION_NAME,
            'license_file_name': LICENSE_FILE_NAME,
        }

    super(EB_itac, self).install_step(silent_cfg_names_map=silent_cfg_names_map)
```

Thanks,
Cormac.

**Comment by migueldiascosta** [comment]
fixed by https://github.com/easybuilders/easybuild-easyblocks/pull/298, https://github.com/easybuilders/easybuild-easyblocks/pull/399, https://github.com/easybuilders/easybuild-easyblocks/pull/487
