### ISSUE TITLE
Failed to determine egg dir path for easybuild-easyconfigs

### ISSUE THREAD

**Issue by DimitriSteyaert** [easybuilders/easybuild#31]
Hi,

I have followed the installation instructions as described at https://github.com/hpcugent/easybuild/wiki/Installing-environment-modules-without-root-permissions. I have downloaded the file bootstrap_eb.py, exported EASYBUILD_PREFIX to /tmp (I also tried $home/tmp, a folder created in my home dir) but when I execute "python bootstrap_eb.py $EASYBUILD_PREFIX" I get the following message:

```
[[INFO]] Found module command 'modulecmd' (EnvironmentModulesC), so using it.
[[INFO]]

+++ STAGE 0: installing distribute via included (patched) distribute_setup.py...


Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
Extracting in /tmp/tmpYNIUCb
Now working in /tmp/tmpYNIUCb/distribute-0.6.34
Installing Distribute
[[INFO]]

+++ STAGE 1: installing EasyBuild in temporary dir with easy_install...


[[ERROR]] Failed to determine egg dir path for easybuild-easyconfigs in /tmp/tmpIcMZ6q/eb_stage1 (subdirs: [])
```

A bit more info on my system:
- RHEL 6.5
- Python 2.6.6
- Environment-modules 3.2.10
- Tcl 8.5.15

Could you explain to me what can be done to fix this?

**Comment by migueldiascosta** [comment]
assuming this is no longer relevant
