### ISSUE TITLE
need c++11 flags for recent openfoam versions

### ISSUE THREAD

**Issue by olesenm** [easybuilders/easybuild#327]
Obviously a hack since these extra flags also go to the C-compiler, but just for the general idea....

    --- a/easybuild/easyblocks/o/openfoam.py
    +++ b/easybuild/easyblocks/o/openfoam.py
    @@ -136,7 +136,8 @@ class EB_OpenFOAM(EasyBlock):
                 if get_software_version('GCC') >= LooseVersion('4.8'):
                     # make sure non-gold version of ld is used, since OpenFOAM requires it
                     # see http://www.openfoam.org/mantisbt/view.php?id=685
    -                extra_flags = '-fuse-ld=bfd'
    +                # Need C++11 for newer OpenFOAM
    +                extra_flags = '-fuse-ld=bfd -std=c++11'
     
                 # older versions of OpenFOAM-Extend require -fpermissive
                 if 'extend' in self.name.lower() and LooseVersion(self.version) < LooseVersion('2.0'):

**Comment by wpoely86** [comment]
@olesenm This is something you should do in the easyconfig. For example, in the easyconfig for `OpenFOAM-4.0-intel-2016b.eb`
```
toolchainopts = {'cstd': 'c++11'}
```

**Comment by wpoely86** [comment]
@olesenm If you're interested, I needed OpenFOAM 4.1 myself and it can be found at hpcugent/easybuild-easyconfigs#4476

**Comment by boegel** [comment]
@olesenm Let us know if this clarifies things for you.

@wpoely86 Maybe we should resolve this in the OpenFOAM easyblock with a version check instead, rather than relying easyconfigs to get this right?
