### ISSUE TITLE
--new-pr after migration?

### ISSUE THREAD

**Issue by JackPerdue** [easybuilders/easybuild#355]
This worked:
<pre>
[j-perdue@terra2 2017b]$ eb -D --github-user=JackPerdue --new-pr --pr-desc="cleanups for GCC 6.4.0"   /sw/eb/ebfiles_repo_cleaned/terra/GCC/GCC-6.4.0-2.28.eb 
== temporary log file in case of crash /tmp/j-perdue/tmp/eb-cot2qk/easybuild-QK5xl4.log
== resolving dependencies ...
== fetching branch 'develop' from https://github.com/hpcugent/easybuild-easyconfigs.git...
== copying easyconfigs to /tmp/j-perdue/tmp/eb-cot2qk/git-working-dir79RW5h/easybuild-easyconfigs...

Opening pull request [DRY RUN]
* target: hpcugent/easybuild-easyconfigs:develop
* from: JackPerdue/easybuild-easyconfigs:20170707143904_new_pr_GCC640
* title: "{compiler}[dummy/] GCC v6.4.0"
* description:
"""
(created using `eb --new-pr`)
cleanups for GCC 6.4.0
"""
* overview of changes:
 easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-6.4.0.eb        | 13 ++++++++-----
 easybuild/easyconfigs/b/Bison/Bison-3.0.4.eb                      | 19 +++++++++++++------
 easybuild/easyconfigs/b/binutils/binutils-2.28-GCCcore-6.4.0.eb   |  8 ++++++--
 easybuild/easyconfigs/b/binutils/binutils-2.28.eb                 |  8 ++++++--
 easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-6.4.0.eb          | 16 +++++++++++-----
 easybuild/easyconfigs/f/flex/flex-2.6.4.eb                        | 30 ++++++++++++++++++++++++++++++
 easybuild/easyconfigs/g/GCC/GCC-6.4.0-2.28.eb                     | 14 ++++++++++----
 easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0.eb                  | 18 +++++++++++-------
 easybuild/easyconfigs/h/help2man/help2man-1.47.4-GCCcore-6.4.0.eb |  8 ++++++--
 easybuild/easyconfigs/h/help2man/help2man-1.47.4.eb               |  9 +++++++--
 easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-6.4.0.eb             | 20 +++++++++++++-------
 easybuild/easyconfigs/m/M4/M4-1.4.18.eb                           | 17 ++++++++++-------
 easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-6.4.0.eb         | 20 +++++++++++++-------
 easybuild/easyconfigs/z/zlib/zlib-1.2.11.eb                       | 18 ++++++++++++------
 14 files changed, 156 insertions(+), 62 deletions(-)
</pre>

This didn't:

<pre>
[j-perdue@terra2 2017b]$ eb --github-user=JackPerdue --new-pr --pr-desc="cleanups for GCC 6.4.0"   /sw/eb/ebfiles_repo_cleaned/terra/GCC/GCC-6.4.0-2.28.eb 
== temporary log file in case of crash /tmp/j-perdue/tmp/eb-JCTJmz/easybuild-DXXzJ0.log
== resolving dependencies ...
== fetching branch 'develop' from https://github.com/hpcugent/easybuild-easyconfigs.git...
== copying easyconfigs to /tmp/j-perdue/tmp/eb-JCTJmz/git-working-dir4poh3W/easybuild-easyconfigs...

Opening pull request
* target: hpcugent/easybuild-easyconfigs:develop
* from: JackPerdue/easybuild-easyconfigs:20170707144011_new_pr_GCC640
* title: "{compiler}[dummy/] GCC v6.4.0"
* description:
"""
(created using `eb --new-pr`)
cleanups for GCC 6.4.0
"""
* overview of changes:
 easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-6.4.0.eb        | 13 ++++++++-----
 easybuild/easyconfigs/b/Bison/Bison-3.0.4.eb                      | 19 +++++++++++++------
 easybuild/easyconfigs/b/binutils/binutils-2.28-GCCcore-6.4.0.eb   |  8 ++++++--
 easybuild/easyconfigs/b/binutils/binutils-2.28.eb                 |  8 ++++++--
 easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-6.4.0.eb          | 16 +++++++++++-----
 easybuild/easyconfigs/f/flex/flex-2.6.4.eb                        | 30 ++++++++++++++++++++++++++++++
 easybuild/easyconfigs/g/GCC/GCC-6.4.0-2.28.eb                     | 14 ++++++++++----
 easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0.eb                  | 18 +++++++++++-------
 easybuild/easyconfigs/h/help2man/help2man-1.47.4-GCCcore-6.4.0.eb |  8 ++++++--
 easybuild/easyconfigs/h/help2man/help2man-1.47.4.eb               |  9 +++++++--
 easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-6.4.0.eb             | 20 +++++++++++++-------
 easybuild/easyconfigs/m/M4/M4-1.4.18.eb                           | 17 ++++++++++-------
 easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-6.4.0.eb         | 20 +++++++++++++-------
 easybuild/easyconfigs/z/zlib/zlib-1.2.11.eb                       | 18 ++++++++++++------
 14 files changed, 156 insertions(+), 62 deletions(-)

Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/general/sw/eb/sw/EasyBuild/3.3.0/lib/python2.7/site-packages/easybuild_framework-3.3.0-py2.7.egg/easybuild/main.py", line 478, in <module>
    main()
  File "/general/sw/eb/sw/EasyBuild/3.3.0/lib/python2.7/site-packages/easybuild_framework-3.3.0-py2.7.egg/easybuild/main.py", line 401, in main
    commit_msg=options.pr_commit_msg)
  File "/sw/eb/sw/EasyBuild/3.3.0/lib/python2.7/site-packages/easybuild_framework-3.3.0-py2.7.egg/easybuild/tools/github.py", line 926, in new_pr
    status, data = pulls_url.post(body=body)
  File "/sw/eb/sw/EasyBuild/3.3.0/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 144, in post
    return self.request(self.POST, url, json.dumps(body), headers, content_type='application/json')
  File "/sw/eb/sw/EasyBuild/3.3.0/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 175, in request
    conn = self.get_connection(method, url, body, headers)
  File "/sw/eb/sw/EasyBuild/3.3.0/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 206, in get_connection
    connection = self.opener.open(request)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 635, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/lib64/python2.7/urllib2.py", line 596, in redirect_request
    raise HTTPError(req.get_full_url(), code, msg, headers, fp)
urllib2.HTTPError: HTTP Error 307: Temporary Redirect
[j-perdue@terra2 2017b]$ 
</pre>

Any ideas?  I know I need to update some file to point to new location but I thought there were forwarders for now.

Either way, suggestions welcome.

**Comment by boegel** [comment]
@JackPerdue This was reported earlier in https://github.com/easybuilders/easybuild-framework/issues/2257, and fixed rather quickly in https://github.com/easybuilders/easybuild-framework/pull/2258.

The redirect is there, it's just not getting handled nicely by the code.

You can either apply the change in https://github.com/easybuilders/easybuild-framework/pull/2258/files#diff-ccf1e273d8604bc208900aa7330c80aa as a hotfix, or just use `eb --pr-target-account=easybuilders --new-pr ...` (or do an `export EASYBUILD_PR_TARGET_ACCOUNT=easybuilders` followed by `eb --new-pr ...`) for now.

The fixes will be included in EasyBuild v3.3.1, which I plan to release mid next week.

**Comment by JackPerdue** [comment]
Thanks Kenneth.  PR added: https://github.com/easybuilders/easybuild-easyconfigs/pull/4836
