### ISSUE TITLE
Minor problem pasting token to eb --install-github-token

### ISSUE THREAD

**Issue by schiotz** [easybuilders/easybuild#357]
Hi,

When following your guide to github integration, I could not get `eb --install-github-token` to accept my newly-generated token.  It turns out that when you copy the token from the github page, an extra space is added to the beginning of the token.  You cannot see this when you paste it into `eb`, but it causes it to reject the token.  Since you probably cannot fix the github page, perhaps you can fix `eb` and have it strip leading or trailing whitespace from the token?

/Jakob

**Comment by boegel** [comment]
Hmm, first time I hear this popping up...

We can definitely `strip` the token value being provided, it's just weird that this hasn't popped up earlier.

**Comment by schiotz** [comment]
@boegel That could be because the intelligent user clicks the "copy to clipboard" button, whereas I double-clicked the actual text and pressed Command-C.  :)

The latter included an extra space in the token ?!?

**Comment by boegel** [comment]
token is stripped from spaces now, change implemented in https://github.com/easybuilders/easybuild-framework/pull/2270
