### ISSUE TITLE
Failed builds using the foss-2016b toolchain

### ISSUE THREAD

**Issue by pol** [easybuilders/easybuild#363]
Tried installing a bio package which failed, I reverted to using foss-2016a which worked.  Filed it in the back of my head to report back if it failed again, which it did.  The first time (it was for HTSeq) it failed on "undefined symbol: PyUnicodeUCS2_Decode".  Which looks like the python is compiled with an older version of Unicode than is required. 

In this case, it can't find the source file:

```
[easybuild@hyalite ~]$ eb HDF5-1.8.18-intel-2016b.eb --robot
<fail>
[easybuild@hyalite ~]$ grep ERROR /tmp/eb-NAxs6s/easybuild-HDF5-1.8.18-20170712.112507.NAlim.log
EasyBuild crashed with an error (at ?:124 in __init__): Couldn't find file hdf5-1.8.18.tar.gz anywhere, and downloading it didn't work either... Paths attempted...<SNIP>https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.18.tar.gz, https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-%(versions)/src/hdf5-1.8.18.tar.gz
```

Checked the URLS, and neither exists.  The current18 folder now only contains hdf5-1.8.19.tar.gz, and the specific version URL should actually be (I think):  https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-$(versions)/src/

Manually downloading the file to the "sources" directory solved the issue.

**Comment by pol** [comment]
I posted this to the wrong place, it should be in easyconfigs.  I will repost.

**Comment by boegel** [comment]
(see https://github.com/easybuilders/easybuild-easyconfigs/issues/4882)
