### ISSUE TITLE
eb unable to download LAPACK-3.6.0

### ISSUE THREAD

**Issue by jacorvar** [easybuilders/easybuild#366]
Hi, I get the following when doing `eb OpenBLAS-0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0.eb`:

`== FAILED: Installation ended unsuccessfully (build directory: /usr/local/easybuild/.local/easybuild/build/OpenBLAS/0.2.15/GCC-4.9.3-2.25-LAPACK-3.6.0): build failed (first 300 chars): Couldn't find file lapack-3.6.0.tgz anywhere, and downloading it didn't work either... Paths attempted (in order): /usr/local/easybuild/.local/easybuild/software/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.3.1-py2.7.egg/easybuild/easyconfigs/o/OpenBLAS/o/OpenBLAS/lapack-3.6.0`

The log tells me:

`WARNING IOError occurred while trying to download http://www.netlib.org/lapack/lapack-3.6.0.tgz`

**Comment by boegel** [comment]
@jacorvar If something goes wrong upstream, there's little EasyBuild can do about it.

I just tried the download myself, works fine now (at least for me).

What you can do is download the tarball manually yourself, and store it where EasyBuild keeps source tarballs. See `eb --show-config` to check the location of the "source path" (see http://easybuild.readthedocs.io/en/latest/Configuration.html#sourcepath), and copy `lapack-3.6.0.tgz` to `<source path>/o/OpenBLAS/`.
