### ISSUE TITLE
Broken links on EB website

### ISSUE THREAD

**Issue by paulmelis** [easybuilders/easybuild#371]
Not sure if this is the right place to report this, but some of the links on https://easybuilders.github.io/easybuild/ are broken:
- Slides from easybuild tutorial at prace summer school -> 404
- Link to Presentation materials of SC15 BoF works, but links on that page to lightning talks etc. are broken

**Comment by boegel** [comment]
This is indeed the right place to report this, thank you, I'll see if I can get these problems fixed...

**Comment by boegel** [comment]
Links are fixed, thanks again for reporting this @paulmelis!
