### ISSUE TITLE
Module fails to build with EASYBUILD_DETECT_LOADED_MODULES=unload

### ISSUE THREAD

**Issue by schiotz** [easybuilders/easybuild#380]
I usually set  EASYBUILD_DETECT_LOADED_MODULES=unload so I can build modules in the same environment that I use normally (I only build modules for my own user).

I now notice that I get problems with modules using the foss/2016b toolchain, if I also have that toolchain loaded.  In this case, it gets unloaded when `eb`  starts, but it is not loaded again properly when the .eb file is build.  I can see with top that the system-wide gcc compiler is used instead of the one in GCC/5.4.0-2.26

Steps to reproduce (with easybuild 3.4.0):
```
export EASYBUILD_DETECT_LOADED_MODULES=unload
module load foss/2016b
eb Python-3.5.2-foss-2016b.eb -r --rebuild
```

The build fails with a linkage error, and I can see during the build phase that GCC 4.something is being used.  In the log file, /usr/bin/ld complains about an illegal relocation.

With no modules loaded, it works as expected.

**Comment by schiotz** [comment]
Follow-up:  
```
$ module --version

Modules based on Lua: Version 6.5.1  2016-08-17 15:44
    by Robert McLay mclay@tacc.utexas.edu
```

**Comment by boegel** [comment]
Ugh, seems like this was never picked up...

@schiotz Is this still a problem?

**Comment by schiotz** [comment]
@boegel 
Sorry about being slow to respond.  I stopped using `EASYBUILD_DETECT_LOADED_MODULES=unload` due to this issue, and have been using `error` instead, and manually unloading modules (not a big hazzle).  So I had lost track of whether this was still an issue.

I just checked, and it looks like this issue has been resolved in modern versions of EasyBuild. :-)
