### ISSUE TITLE
Dep graph hint on necessary python module gv incorrect

### ISSUE THREAD

**Issue by paulmelis** [easybuilders/easybuild#389]
While trying to generate some dependency graph pictures with `--dep-graph` EB reported a missing Python module called `gv`:

```
ERROR: ImportError: None of the specified modules gv is available; required module 'gv' is not available (provided by Python package graphviz, available from https://pypi.python.org/pypi/graphviz)
```

But the suggested PyPI package `graphviz` is actually *not* the package that provides the `gv` module, as the PyPi package `graphviz` provides the module `graphviz` (see https://pypi.python.org/pypi/graphviz).

The `gv` module that EB uses is part of the Python bindings of the graphviz tool itself. Although there's a PyPi entry for `graphviz-python` (https://pypi.python.org/pypi/graphviz-python) it can unfortunately not be installed with PyPi and needs something like a OS-level graphviz package.

This is with EB 3.4.0, btw.

**Comment by paulmelis** [comment]
Btw, there's an easyconfig for graphviz including python bindings, of course :smile:

**Comment by boegel** [comment]
@paulmelis Thanks for the bug report!

The error message should indeed mention https://pypi.python.org/pypi/graphviz-python, which does indeed require Graphviz to be available already.

**Comment by boegel** [comment]
fixed in https://github.com/easybuilders/easybuild-framework/pull/2340
