### ISSUE TITLE
broken wiki link (Contributing-back)

### ISSUE THREAD

**Issue by tutufan** [easybuilders/easybuild#403]
Don't think I can fix this myself, but there's a broken wiki link on this page.  Probably a missing hyphen.  It should be `Contributing-back`?

https://github.com/easybuilders/easybuild/wiki/Review-process-for-contributions

```
Contributions to EasyBuild, made via [pull requests](Contributing back), are thoroughly
```

**Comment by boegel** [comment]
@tutufan I fixed the broken link, but you should really look at http://easybuild.readthedocs.io/en/latest/Contributing.html instead (as is mentioned on the top of the page where the now fixed link points to)

**Comment by tutufan** [comment]
Oops.  :-)

Thanks!
