### ISSUE TITLE
How can I trim the EasyBuild directory to the minimum?

### ISSUE THREAD

**Issue by jdmedeiros** [easybuilders/easybuild#406]
First of all, congratulations on achieving the unthinkable with EasyBuild. This is an awesome product... (also a nightmare for a sysdmin)!

Once I am done building the modules that I need, how can I cleanup the EasyBuild directory leaving only what is necessary at runtime?  In my view, once you "run timed it" you would be able to use the modules you built up to that moment, but would not be able to build any other modules.

Thanks!

**Comment by ocaisa** [comment]
There is currently no way to uninstall something from EasyBuild, everything needs to be removed manually. There's a good reason for this, EB has no way of telling whether an installation is required by something else it has built (it cannot currently do a reverse lookup on installed modules). More importantly it can't tell if a *user* is leveraging the software, so uninstalling is something that users should (somehow) be warned about.

Honestly though, I don't fully understand what you are asking. Unless you are building the runtime stack statically there isn't that much you can safely delete, it's a web of dependencies...which is kind of why EasyBuild is useful in the first place.

**Comment by ocaisa** [comment]
EB does flag `builddependencies`, so if something is consistently used as build dependency (like `CMake` and `Autotools`) you could safely remove them. They are a small minority though and you would still have to manually find and remove them...

**Comment by jdmedeiros** [comment]
Thank you, got it!
