### ISSUE TITLE
build failed ... Couldn't find file mpc-1.0.1.tar.gz anywhere...

### ISSUE THREAD

**Issue by ndusek** [easybuilders/easybuild#409]
**EasyBuild version**: 3.5.1
**Modules type**:  Tcl Environment Modules, v3.2.10
**OS**:  CentOS 6.8

We have EasyBuild installed and configured with the required options. Commands like `eb -S [software]` and `eb [easybuild-file] -Dr` work, but the out-of-the-box [WRF install referenced in the docs](http://easybuild.readthedocs.io/en/latest/Typical_workflow_example_with_WRF.html) is failing with the following trace:

```
== building and installing GCC/4.7.2...
== fetching files...
== FAILED: Installation ended unsuccessfully (build directory: /home/ndusek/easybuild/build/GCC/4.7.2/dummy-dummy): build failed (first 300 chars): Couldn't find file mpc-1.0.1.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order):
```
I've left out the specific paths, but any clue as to what the problem is here? I figure it must be something basic I'm missing since GCC should be pretty easy to install.

**Comment by boegel** [comment]
The problem is that MPC has changed the download locations. This is already fixed in our develop branch, see https://github.com/easybuilders/easybuild-easyconfigs/pull/5662.

To work around this, you can download the tarball manually to the location that EasyBuild would (see ‘sourcepath’ in the output of ‘eb --show-config’)

**Comment by ndusek** [comment]
Ok, thank you. I was about to post a comment saying I worked around it by modifying the source URL in the .eb file and that seems to have worked. I will consider the above approach for future fixes as well.
