### ISSUE TITLE
Building/Bootstrapping easybuild fails on Alpine Linux (MUSL LIBC): Failed to determine glibc version

### ISSUE THREAD

**Issue by alainvanhoof** [easybuilders/easybuild#410]
[[INFO]] +++ STAGE 2: installing EasyBuild in /home/vagrant/.local/easybuild with EasyBuild from stage 1...

Traceback (most recent call last):
  File "bootstrap_eb.py", line 1047, in <module>
    main()
  File "bootstrap_eb.py", line 850, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "bootstrap_eb.py", line 717, in stage2
    easybuild_main()
  File "/tmp/tmpy5Jl9M/eb_stage1/lib/python2.7/site-packages/easybuild_framework-3.5.1-py2.7.egg/easybuild/main.py", line 198, in main
    init_session_state = session_state()
  File "/tmp/tmpy5Jl9M/eb_stage1/lib/python2.7/site-packages/easybuild_framework-3.5.1-py2.7.egg/easybuild/tools/testing.py", line 137, in session_state
    'system_info': get_system_info(),
  File "/tmp/tmpy5Jl9M/eb_stage1/lib/python2.7/site-packages/easybuild_framework-3.5.1-py2.7.egg/easybuild/tools/systemtools.py", line 663, in get_system_info
    'glibc_version': get_glibc_version(),
  File "/tmp/tmpy5Jl9M/eb_stage1/lib/python2.7/site-packages/easybuild_framework-3.5.1-py2.7.egg/easybuild/tools/systemtools.py", line 645, in get_glibc_version
    glibc_ver_str, glibc_ver_regex.pattern)
easybuild.tools.build_log.EasyBuildError: "Failed to determine glibc version from 'UNKNOWN' using pattern '^ldd \\([^)]*\\) (\\d[\\d.]*).*$'."

**Comment by boegel** [comment]
Well, this is new...

@alainvanhoof What does `ldd --version` print? What would be the proper way to determine the `glibc` version on Alpine Linux?

**Comment by alainvanhoof** [comment]
Hi, wow fast reaction.

output of ldd --version:

$ ldd --version
musl libc (x86_64)
Version 1.1.18
Dynamic Program Loader
Usage: ldd [options] [--] pathname
$

Note that Alpine Linux is MUSL-LIBC and by default there is no glibc on the OS.

if I do:

pip install easybuild

I get the same error:

$ eb
ERROR: Failed to determine glibc version from 'UNKNOWN' using pattern '^ldd \([^)]*\) (\d[\d.]*).*$'.

Cheers,
Alain

**Comment by boegel** [comment]
@alainvanhoof The problem is basically that we're not expecting output like this from `ldd --version`, and we're clearly not dealing well with seeing something different...

It seems like you're the first person trying to use EasyBuild on a non-glibc Linux system.

We're expecting something like this:

```
$ ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
...
```

where we can grab the version from the line that starts with `ldd`.

The problem is here: https://github.com/easybuilders/easybuild-framework/blob/master/easybuild/tools/systemtools.py#L636

Can you try changing that line to this in the `pip`-installed EasyBuild, in `easybuild/tools/systemtools.py`, to this:

```
glibc_ver_regex = re.compile(r"(?:ldd|Version)\s*\(?[^)]*\)? (\d[\d.]*).*$")
```

**Comment by alainvanhoof** [comment]
Hi Kenneth,

Besides an other output, it also does not support really support the --version option as you can see in the output of the previous mail.

        #glibc_ver_regex = re.compile(r"^ldd \([^)]*\) (\d[\d.]*).*$")
        glibc_ver_regex = re.compile(r"(?:ldd|Version)\s*\(?[^)]*\)? (\d[\d.]*).*$")

dev-build01:~# eb
ERROR: Failed to determine glibc version from 'UNKNOWN' using pattern '(?:ldd|Version)\s*\(?[^)]*\)? (\d[\d.]*).*$'.
dev-build01:~#

Cheers,
Alain

**Comment by boegel** [comment]
What do you mean by "does not support really support the --version option"? `ldd --version` spits out output that includes the version, no?

Maybe it exits with a non-zero exit code though? What does `echo $?` print right after running `ldd --version`?

I guess we're going to have to add custom detection for MUSL libc, and be less strict about not recognising the libc version on the system...

**Comment by alainvanhoof** [comment]
Hi Kenneth,

I was thinking the same and test for $? on the commands:

dev-build01:~$ ldd --version
musl libc (x86_64)
Version 1.1.18
Dynamic Program Loader
Usage: ldd [options] [--] pathname
dev-build01:~$ echo $?
1
dev-build01:~$ ldd
musl libc (x86_64)
Version 1.1.18
Dynamic Program Loader
Usage: ldd [options] [--] pathname
dev-build01:~$ echo $?
1
dev-build01:~$ ldd /usr/bin/python
	/lib/ld-musl-x86_64.so.1 (0x78bb895a2000)
	libpython2.7.so.1.0 => /usr/lib/libpython2.7.so.1.0 (0x78bb88ffc000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x78bb895a2000)
dev-build01:~$ echo $?
0
dev-build01:~$

Cheers,
Alain.

**Comment by boegel** [comment]
Does musl libc accept some other option to just spit out the version? Maybe check it's manpage?

`ldd -v` perhaps? Ideally, we should try and find something that exits with `0`

**Comment by alainvanhoof** [comment]
There is no man page (When I install the man-pages on Alpine Linux I get the gnu-ldd version).

I don’t think there are any options it just prints the DSO info or displays version with ERROR_LEVEL 1. On the interweb I found more projects crashing on the ERROR_LEVEL of the MUSL LIBC ldd.

"musl’s dynamic linker comes with ldd functionality built in. Just create a symlink from ld-musl-$ARCH.so to /bin/ldd. If the dynamic linker was started as “ldd”, it will detect that and print the appropriate DSO information.”

Cheers,
Alain.

**Comment by boegel** [comment]
OK, I think our best way out is to avoid EasyBuild crashing hard. You can change the `raise EasyBuildError(...)` to `_log.warning(...)` followed by a `return UNKNOWN` in `get_glibc_version` (like we do on macOS).

**Comment by alainvanhoof** [comment]
Nice, thanks,

Will this be a change in the “official” source to?

Cheers,
Alain

**Comment by alainvanhoof** [comment]
Create a pull request

**Comment by boegel** [comment]
@alainvanhoof We can certainly make this change part of the next EasyBuild release, I see reason not to.

Let's follow up in https://github.com/easybuilders/easybuild-framework/pull/2397 .
