### ISSUE TITLE
error with toolchain gimkl

### ISSUE THREAD

**Issue by sdesrozis** [easybuilders/easybuild#421]
Hello,
I would like to use a toolchain gimkl, meanning GCC + Intel MKL + [Intel](url) MPI. I have modified a HDF5 1.8.20 easybuild to enable gimkl-2017b toolchain (more or less equal to 2017a) and I have the following error during build step : 

# error "This Intel <math.h> is for use with only the Intel compilers!"
 
You can check that CPPFLAGS includes mkl headers (here math.h, but also intrinsics etc.) which are not compatible with GCC. These headers replace legacy ones but are for icc compilers. CPPFLAGS contains too much headers (ok with intel icc compiler but not gcc).  

export CPPFLAGS="-I/tmp/install/software/MPI/GCC/6.4.0-2.28/impi/2017.3.196/imkl/2017.3.196/include -I/tmp/install/software/MPI/GCC/6.4.0-2.28/impi/2017.3.196/imkl/2017.3.196/mkl/include -I/tmp/install/software/MPI/GCC/6.4.0-2.28/impi/2017.3.196/imkl/2017.3.196/include -I/tmp/install/software/Compiler/GCCcore/6.4.0/zlib/1.2.11/include -I/tmp/install/software/Compiler/GCCcore/6.4.0/Szip/2.1.1/include"

The header /tmp/install/software/MPI/GCC/6.4.0-2.28/impi/2017.3.196/imkl/2017.3.196/include should not be included with GCC.

I tried prebuildopts and preconfigopts ('unset CPPFLAGS && ') but it doesn't work with python extensions... 

Any idea to fix that issue ??

**Comment by sdesrozis** [comment]
post in framework project. Sorry.

**Comment by boegel** [comment]
see follow-up in #2469
