### ISSUE TITLE
easy_install removed from setuptools

### ISSUE THREAD

**Issue by mcakircali** [easybuilders/easybuild#454]
Since python-setuptools 39.0.1-2 on Ubuntu, the "easy_install" is removed from the package.

check_setuptools finds the "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.pyc" file but the "easy_install" is not there on the commandline.

Result:
[[ERROR]] Failed to find right 'easy_install' command!

**Comment by boegel** [comment]
@mcakircali Same problem as reported in https://github.com/easybuilders/easybuild-framework/issues/2581, let's follow up there (since the bootstrap script is hosted in the `easybuild-framework` repository).

I'll try and get this fixed soon.
