### ISSUE TITLE
Python-3.6.6-foss-2018b.eb : fail to import scipy.special

### ISSUE THREAD

**Issue by guest1604** [easybuilders/easybuild#476]
After installing `Python-3.6.6-foss-2018b.eb`, on CentOS 7 with EasyBuild 3.8.0, I have an issue when importing `scipy.special` python module.

```
$ module purge
$ module load GCC/7.3.0-2.30 OpenMPI/3.1.1 Python/3.6.6
Python 3.6.6 (default, Dec 21 2018, 07:27:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.special
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/easybuild/software/MPI/GCC/7.3.0-2.30/OpenMPI/3.1.1/Python/3.6.6/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-x86_64.egg/scipy/special/__init__.py", line 640, in <module>
    from ._ufuncs import *
ImportError: /home/user/.local/easybuild/software/MPI/GCC/7.3.0-2.30/OpenMPI/3.1.1/Python/3.6.6/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-x86_64.egg/scipy/special/_ufuncs.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _gfortran_stop_numeric_f08

```
**I think this issue is related to `EB_scipy` or `FortranPythonPackage` easyblocks but I don't know how to fix it.**

Below, my workaround, but this is not a good solution : 

1. remove temporarly `<...>/easyblocks/s/scipy.py` easyblock in order to use `PythonBundle` easyblock when installing `scipy` extension,

2.  in `Python-3.6.6-foss-2018b.eb`, use this extension :
```
    ('scipy', '1.1.0', {
        'source_tmpl': '%(name)s-%(version)s-cp36-cp36m-manylinux1_x86_64.whl',
        'source_urls': ['https://pypi.python.org/packages/source/s/scipy/'],
        'checksums': ['729f8f8363d32cebcb946de278324ab43d28096f36593be6281ca1ee86ce6559'],
        'use_pip': True,
        'unpack_sources': False,
    }),
```
**This is not the good solution for this issue, but I would like to know if there is an option to force an extension to use a specific easyblock.**

Thanks for your help !

**Comment by boegel** [comment]
follow-up in https://github.com/easybuilders/easybuild-easyconfigs/issues/7340
