### ISSUE TITLE
Packages needed for --check-contrib

### ISSUE THREAD

**Issue by henkela** [easybuilders/easybuild#483]
Which Python-Packages are needed for --check-contrib --check-style to work? 
- pep8

**Comment by boegel** [comment]
@henkela Sorry for not answering your question here...

`pep8` or `pycodestyle` (which is `pep8` rebranded) should be sufficient to make `--check-style` and `--check-contrib` work (and you should get a fairly clear error message if they're not there)

**Comment by boegel** [comment]
Now documented at https://easybuild.readthedocs.io/en/latest/Installation.html#optional-python-packages
