### ISSUE TITLE
Bad performance when compiled with gompi-2018b/2019a

### ISSUE THREAD

**Issue by K-Wone** [easybuilders/easybuild#488]
My colleagues and I built a SLURM cluster consisting of a login node (*nlogin*), a data node (*ndata*) and several compute nodes (*n1-nX*). The nodes have two different kinds of chips: Xeon E2620v3 and E2620v4. The data node has two E2620v4 (may be Broadwell) processors and the login node has two E2620v3 (Haswell) processors.

Lmod and Easybuild are amazing and we deployed them on *ndata*. The file system on node ndata, which includes Lmod, Easybuild, software sources, module caches, etc. on it, is shared by other nodes via NFS. 

We've built and installed multiple versions of MPI implementations by running the `eb` command on the related toolchains (with --optarch=GENERIC) and all of them works well with SLURM and Lmod. Here's the list:
- gompi: 2016b, 2018b, 2019a
- gmpich: 2016a, 2017.08
- intel: 2018a, 2018b, 2019a
- iompi: 2019.01
- gimpi: 2018a
- foss: 2018a, 2019a

Then we tried to do some tests on different MPI implementations. However, we found that our codes slowed down extremely when compiled with toolchains dependent on GCC-7.X.X or GCC-8.2.0.

 This is how we did:
- The test code is picked from the MPI 3.2.1 source directory `mpi-3.2.1/examples/`. It's called `cpi.c`, a simple code used to compute PI in parallel.
- We did some modifications to the code to make it to support OpenMP and print more information.
- The code was compiled on *nlogin* with every toolchains we built.
- The code was multithreaded and then was submitted to SLURM to run on 4 nodes with 8 MPI ranks in total. The options passed to mpirun worked well cause each node had the correct task affinity.
- The code also excuted on the local host, *nlogin*.

It seems that the toolchains based on GCC-7.X.X or GCC-8.2.0 slow down our code somehow.

I built some toolchains myself (by modified easyconfigs) for a comparison:
- gompi-2018o: GCC-6.4.0, OpenMPI-3.1.3
- gompi-2019o: GCC-6.4.0, OpenMPI-4.0.0
- gompi-4.0.0-GCC-8.2.0: GCC-8.2.0, OpenMPI-4.0.0
- gmpich-2017o: GCC-6.4.0, MPICH-3.2.1
- gmpich-3.2-GCC-7.2.0: GCC-7.2.0, MPICH-3.2

as well as a toolchain with icc:
- impich-2018o: icc/ifort-2018.3.222, MPICH-3.2.1

```
    Wall time: 245.53   (./hybridPI-intel-2018a-icc, P:8, T:12)
    Wall time: 245.53   (./hybridPI-intel-2018b-icc, P:8, T:12)
    Wall time: 245.62   (./hybridPI-intel-2019a-icc, P:8, T:12)
    Wall time: 289.96   (./hybridPI-gimpi-2018a, P:8, T:12)

    Wall time: 308.35   (./hybridPI-gmpich-2016a, P:8, T:12)
    Wall time: 546.53   (./hybridPI-gmpich-2017.08, P:8, T:12)
    Wall time: 288.03   (./hybridPI-gmpich-2017o, P:8, T:12)
    Wall time: 546.41   (./hybridPI-gmpich-3.2-GCC-7.2.0, P:8, T:12)

    Wall time: 292.58   (./hybridPI-gompi-2016b, P:8, T:12)
    Wall time: 286.86   (./hybridPI-gompi-2018a, P:8, T:12)
    Wall time: 546.15   (./hybridPI-gompi-2018b, P:8, T:12)
    Wall time: 489.95   (./hybridPI-gompi-2019a, P:8, T:12) 
    Wall time: 245.63   (./hybridPI-iompi-2019.01, P:8, T:12)

    Wall time: 245.62   (./hybridPI-impich-2018o, P:8, T:12)
    Wall time: 288.54   (./hybridPI-gompi-2019o, P:8, T:12)
    Wall time: 291.23   (./hybridPI-gompi-2018o, P:8, T:12)
    Wall time: 489.86   (./hybridPI-gompi-4.0.0-GCC-8.2.0, P:8, T:12)
 
    Wall time: 286.51   (./hybridPI-foss-2018a, P:8, T:12)
    Wall time: 490.36   (./hybridPI-foss-2019a, P:8, T:12)
```

> `P:8, T:12` indicates the number of MPI ranks and OpenMP threads.

Any idea?

**Comment by boegel** [comment]
The main difference between `gompi/2018b` and `gompi/2018a` is the OpenMPI major version (`3.1.1` in `2018b` vs `2.1.2` in `2018a`), I would say that's the first suspect to look into...

Although the test you did with `gmpich/2017.08` vs `gmpich/2017o` (where the only difference is the GCC version being used) does seem to suggest that the compiler is to blame...
Maybe some default setting changed there that you need to be aware of?

How was your example compiled exactly?

**Comment by boegel** [comment]
pinging @besserox, who has quite a bit of experience with playing around with MPI libraries...

**Comment by K-Wone** [comment]
**Easyconfigs**

I thought it was the MPI version. The difference between `gompi/2018a` and `gompi/2018b` made me configure another customized toolchain, `gompi/2018o`, for testing.

```
easyblock = "Toolchain"

name = 'gompi'
version = '2018o'

homepage = '(none)'
description = """GNU Compiler Collection (GCC) based compiler toolchain,
 including OpenMPI for MPI support."""

toolchain = {'name': 'dummy', 'version': 'dummy'}

gccver = '6.4.0-2.28'

# compiler toolchain dependencies
dependencies = [
    ('GCC', gccver),  # includes both GCC and binutils
    ('OpenMPI', '3.1.3', '', ('GCC', gccver)),
]

moduleclass = 'toolchain'
```

The customized easyconfigs I built suggest that it possibly has nothing to do with OpenMPI or MPICH but I'm not sure about that. 

**Compilation and execution**

The code is like
```c
// cpi-hybrid.c
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <unistd.h>
#include "mpi.h"
#include "omp.h"

int main(int argc, char *argv[])
{
    int rank, numprocs, numthreads;
    double mypi, pi, h, sum, x;
    double wtime;
    // some declarations...
    char proc_name[MPI_MAX_PROCESSOR_NAME];
    char mpi_name[MPI_MAX_LIBRARY_VERSION_STRING];
    /*
     * initialize and print the version of libs
     */

    /*
     * compute PI and do an MPI_Reduce
     */

    /*
     * print the wall time
     */
    return 0;
}
```

It was compiled with 
```bash
# for gcc
mpicc -fopenmp cpi-hybrid.c -o hybridPI-${CLASS}-${cl}
# for icc
mpiicc -qopenmp cpi-hybrid.c -o hybridPI-${CLASS}-${cl}
```

The executable was submitted to SLURM with a script
```bash
#!/bash/sh
#SBATCH -N 4
#SBATCH -n 8
#SBATCH --export=ALL,OMP_NUM_THREADS=12
## for OpenMPI
mpirun -bind-to none ./hybridPI-${CLASS}-${cl}
## for the rest
mpirun ./hybridPI-${CLASS}-${cl}
```

> The two variables ${CLASS} and ${cl} are set for identification.

The CPU usage provided by command `top` looks good: 2 processes per node each has 12 threads with 1200% usage in total. That is what I want.

Here is the log. The code printed the version of the MPI libs, especially of MPICH.
[hybridPI-3vers-N4n8t12-555.log](https://github.com/easybuilders/easybuild/files/2898003/hybridPI-3vers-N4n8t12-555.log)

**OpenMPI version**

I can see all of the dependencies when `gompi/2018o` is loaded by Lmod:

```
GCCcore/6.4.0, GCC/6.4.0-2.28, numactl/2.0.11, libxml2/2.9.7, hwloc/1.11.8, gompi/2018o,
binutils/2.28, zlib/1.2.11, XZ/5.2.3, libpciaccess/0.14, OpenMPI/3.1.3
```

Is there something wrong?

Here is what `ompi_info` gives me:

```
## gompi/2019a
 Configured architecture: x86_64-pc-linux-gnu
  Configure command line: '--prefix=/apps/software/Compiler/GCC/8.2.0-2.31.1/OpenMPI/3.1.3' '--build=x86_64-pc-linux-gnu' '--host=x86_64-pc-linux-gnu' '--enable-shared' '--with-verbs' '--enable-mpirun-prefix-by-default' '--with-hwloc=/apps/software/Compiler/GCCcore/8.2.0/hwloc/1.11.11' '--enable-mpi-cxx' '--enable-mpi-thread-multiple'

## gompi/2018o
 Configured architecture: x86_64-pc-linux-gnu
  Configure command line: '--prefix=/apps/software/Compiler/GCC/6.4.0-2.28/OpenMPI/3.1.3' '--build=x86_64-pc-linux-gnu' '--host=x86_64-pc-linux-gnu' '--enable-shared' '--with-verbs' '--enable-mpirun-prefix-by-default' '--with-hwloc=/apps/software/Compiler/GCCcore/6.4.0/hwloc/1.11.8' '--enable-mpi-cxx' '--enable-mpi-thread-multiple'
```

**Comment by K-Wone** [comment]
Maybe the flags `'--enable-mpi-cxx' '--enable-mpi-thread-multiple'` don't matter cause I've been struggling against them for many times. The performance stays no matter they are set or not.

**Comment by boegel** [comment]
@K-Wone Are you deliberately compiling the program with optimizations enabled?

Note that with GCC, the default is to compile with `-O0` (see `-O0` at https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/Optimize-Options.html#Optimize-Options), while with `icc` the default is `-O2`.

This doesn't explain the differences you're seeing though, unless somehow underneath `-O2` was enabled in some cases...

Can you try consistently compiling with `-O2`?

**Comment by K-Wone** [comment]
Probably! I'm working on it.

**Comment by K-Wone** [comment]
It works for me! It seems that they have different flags by default. I've never thought about it :)

Thank you!

**Comment by K-Wone** [comment]
I'm closing this issue. Thanks a lot :)

**Comment by boegel** [comment]
@K-Wone Good to hear you've got it figured out!

It's still weird though that you were seeing better performance with `gompi/2018a` (GCC 6.x and OpenMPI 2.x).

https://gcc.gnu.org/onlinedocs/gcc-6.4.0/gcc/Optimize-Options.html shows that `-O0` is also default with GCC 6.4.0, so I'm not sure why you saw better performance using it...

**Comment by K-Wone** [comment]
Yes. Actually, you can see it with every listed toolchains related to GCC 6.4.0 (gmpich-2017o, gompi-2018a, gompi-2018o, gompi-2019o) if I didn't mess up the easyconfig files.

I made a comparison between `gompi/2018a` and `gompi/2018b`:

```
$ ml gompi/2018a
$ mpicc -fopenmp --showme cpi-hybrid.c -o a.out
gcc -fopenmp cpi-hybrid.c a.out -I/apps/software/Compiler/GCC/6.4.0-2.28/OpenMPI/2.1.2/include -L/apps/software/Compiler/GCCcore/6.4.0/hwloc/1.11.8/lib -Wl,-rpath -Wl,/apps/software/Compiler/GCCcore/6.4.0/hwloc/1.11.8/lib -Wl,-rpath -Wl,/apps/software/Compiler/GCC/6.4.0-2.28/OpenMPI/2.1.2/lib -Wl,--enable-new-dtags -L/apps/software/Compiler/GCC/6.4.0-2.28/OpenMPI/2.1.2/lib -lmpi

$ ml gompi/2018b
$ mpicc -fopenmp --showme cpi-hybrid.c -o a.out
gcc -fopenmp cpi-hybrid.c a.out -I/apps/software/Compiler/GCC/7.3.0-2.30/OpenMPI/3.1.1/include -L/apps/software/Compiler/GCCcore/7.3.0/hwloc/1.11.10/lib -Wl,-rpath -Wl,/apps/software/Compiler/GCCcore/7.3.0/hwloc/1.11.10/lib -Wl,-rpath -Wl,/apps/software/Compiler/GCC/7.3.0-2.30/OpenMPI/3.1.1/lib -Wl,--enable-new-dtags -L/apps/software/Compiler/GCC/7.3.0-2.30/OpenMPI/3.1.1/lib -lmpi
```

**Comment by K-Wone** [comment]
I built almost every toolchain with this command:

```
$ eb toolchain-name.eb -r --optarch=GENERIC
```

None of the easyconfigs has been modified since they were there.

**Comment by K-Wone** [comment]
I'v run several tests. I'm not sure if they could possibly show the difference between `gompi/2018a` and `gompi/2018b` on my machines.

> The number of iterations has been restricted.

```
Opt       intel-2018a    gompi-2018a    gompi-2018b
default          2.47           2.92           5.51
-O2              2.47           2.48           2.51
-O1              2.48           2.47           2.48
-O0              3.85           2.89           5.50
```

**Comment by boegel** [comment]
@K-Wone Maybe try using the `--showme` option for `mpicc`, perhaps that shows a `-O2` (or similar) with earlier OpenMPI versions?
See also https://www.open-mpi.org/faq/?category=mpi-apps#wrapper-showme-with-no-file

**Comment by boegel** [comment]
Ah, nevermind, you actually did already, just saw your previous comment :)

**Comment by K-Wone** [comment]
So, we are quite sure now the optimization is set to `-O0` by default. I've tried to compile the code with underlying `gcc` and `icc` of the toolchains listed in my original comment. I made my script loop over each of the flags: `-O0, -O1, -O2, -O3, -Os, -Og, -Ofast`

The code is executed by only one process without multithread. I think the results remain the same as in the previous comments, again, if I didn't mess anything up. I don't know what it means but it could be avoided by higher optimizations as you said. Maybe it is sufficient :)

```
## O0
    Wall time: 3.39     (./ompPI-O0-intel-2018a-icc, T:1)
    Wall time: 2.80     (./ompPI-O0-intel-2018a-gcc, T:1)
    Wall time: 3.39     (./ompPI-O0-intel-2018b-icc, T:1)
    Wall time: 9.86     (./ompPI-O0-intel-2018b-gcc, T:1)
    Wall time: 3.39     (./ompPI-O0-intel-2019a-icc, T:1)
    Wall time: 9.04     (./ompPI-O0-intel-2019a-gcc, T:1)
    Wall time: 2.80     (./ompPI-O0-gimpi-2018a, T:1)

    Wall time: 2.95     (./ompPI-O0-gmpich-2016a, T:1)
    Wall time: 9.87     (./ompPI-O0-gmpich-2017.08, T:1)
    Wall time: 9.86     (./ompPI-O0-gmpich-3.2-GCC-7.2.0, T:1)
    Wall time: 9.86     (./ompPI-O0-impich-2018o, T:1)
    
    Wall time: 2.71     (./ompPI-O0-gompi-2016b, T:1)
    Wall time: 2.80     (./ompPI-O0-gompi-2018a, T:1)
    Wall time: 9.86     (./ompPI-O0-gompi-2018b, T:1) ****
    Wall time: 9.03     (./ompPI-O0-gompi-2019a, T:1) ****
    Wall time: 9.04     (./ompPI-O0-gompi-2019o, T:1)
    Wall time: 9.03     (./ompPI-O0-iompi-2019.01, T:1)

    Wall time: 2.80     (./ompPI-O0-foss-2018a, T:1)
    Wall time: 9.86     (./ompPI-O0-foss-2018b, T:1)
    Wall time: 9.04     (./ompPI-O0-foss-2019a, T:1)

## O2
    Wall time: 1.17     (./ompPI-O2-intel-2018a-icc, T:1)
    Wall time: 2.34     (./ompPI-O2-intel-2018a-gcc, T:1)
    Wall time: 1.17     (./ompPI-O2-intel-2018b-icc, T:1)
    Wall time: 2.34     (./ompPI-O2-intel-2018b-gcc, T:1)
    Wall time: 1.17     (./ompPI-O2-intel-2019a-icc, T:1)
    Wall time: 2.34     (./ompPI-O2-intel-2019a-gcc, T:1)
    Wall time: 2.34     (./ompPI-O2-gimpi-2018a, T:1)

    Wall time: 2.34     (./ompPI-O2-gmpich-2016a, T:1)
    Wall time: 2.34     (./ompPI-O2-gmpich-2017.08, T:1)
    Wall time: 2.34     (./ompPI-O2-gmpich-3.2-GCC-7.2.0, T:1)
    Wall time: 2.34     (./ompPI-O2-impich-2018o, T:1)

    Wall time: 2.34     (./ompPI-O2-gompi-2016b, T:1)
    Wall time: 2.34     (./ompPI-O2-gompi-2018a, T:1)
    Wall time: 2.34     (./ompPI-O2-gompi-2018b, T:1)
    Wall time: 2.34     (./ompPI-O2-gompi-2019a, T:1)
    Wall time: 2.34     (./ompPI-O2-gompi-2019o, T:1)
    Wall time: 2.34     (./ompPI-O2-iompi-2019.01, T:1)

    Wall time: 2.34     (./ompPI-O2-foss-2018a, T:1)
    Wall time: 2.34     (./ompPI-O2-foss-2018b, T:1)
    Wall time: 2.34     (./ompPI-O2-foss-2019a, T:1)
```
