### ISSUE TITLE
Easyconfigs documentation improvement

### ISSUE THREAD

**Issue by zzotta** [easybuilders/easybuild#491]
I would suggest to add a "Reference" section in the TOC.
May be it could just be a link to the paragraph "Overview of version specific (auto-generated) documentation pages", this last title does not say how important it is.

The pages I struggled to find were

* https://easybuild.readthedocs.io/en/latest/version-specific/easyconfig_parameters.html
* https://easybuild.readthedocs.io/en/latest/version-specific/easyconfig_templates.html

I would say they are among the first ones a package developer should face.

**Comment by ocaisa** [comment]
I've added [a new section](https://easybuild.readthedocs.io/en/develop/Writing_easyconfig_files.html#version-specific-documentation-relevant-to-easyconfigs) that also gets links in the main TOC
