### ISSUE TITLE
binutils, Build error

### ISSUE THREAD

**Issue by HerderB** [easybuilders/easybuild#495]
Hello all,

I'm new to EasyBuild so maybe I'm missing something very obvious here but I'm having troubles installing binutils, which is a requirement for a lot of packages.
During building, I get the following error:

> == FAILED: Installation ended unsuccessfully (build directory: /home/mark.bessem/.local/easybuild/build/binutils/2.30/dummy-): build failed (first 300 chars): cmd " env LIBS='-Wl,-rpath=/usr/lib -Wl,-rpath=/usr/lib64'  make -j 6  CFLAGS="-g -O2 -fPIC" " exited with exit code 2 and output:
> make[1]: Entering directory `/home/mark.bessem/.local/easybuild/build/binutils/2.30/dummy-/binutils-2.30'
> make[1]: Nothing to be done for `all-target'.
> Configuring in ./
> == Results of the build can be found in the log file(s) /tmp/eb-XS7n7W/easybuild-binutils-2.30-20190329.152508.RNXWV.log
> ERROR: Build of /opt/ohpc/pub/libs/easybuild/3.8.1/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.8.1-py2.7.egg/easybuild/easyconfigs/b/binutils/binutils-2.30.eb failed (err: 'build failed (first 300 chars): cmd " env LIBS=\'-Wl,-rpath=/usr/lib -Wl,-rpath=/usr/lib64\'  make -j 6  CFLAGS="-g -O2 -fPIC" " exited with exit code 2 and output:\nmake[1]: Entering directory `/home/mark.bessem/.local/easybuild/build/binutils/2.30/dummy-/binutils-2.30\'\nmake[1]: Nothing to be done for `all-target\'.\nConfiguring in ./')
> 

I've added the full logs as attachment.

If you could tell me what's going wrong exactly and how I could fix this, I would be very grateful.
[easybuild-binutils-2.30-20190329.152508.RNXWV.log](https://github.com/easybuilders/easybuild/files/3023119/easybuild-binutils-2.30-20190329.152508.RNXWV.log)

**Comment by HerderB** [comment]
Hello all,

I've installed binutils manually as a module and hoped this would enable me to progress with the installation chain. Now however, the installation of GCCcore is failing. The problem seems not to lie with binutils itself but with (our installation of) EasyBuild.

I've included the logs of the failed installation again. Could you please help me pinpoint the problem and why I can't install anything using EasyBuild?

> == temporary log file in case of crash /tmp/eb-XbF_uo/easybuild-6MFqy4.log
> == resolving dependencies ...
> == processing EasyBuild easyconfig /opt/ohpc/pub/libs/easybuild/3.8.1/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.8.1-py2.7.egg/easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0.eb
> == building and installing GCCcore/6.4.0...
> == fetching files...
> == creating build dir, resetting environment...
> == unpacking...
> == patching...
> == preparing...
> == configuring...
> == building...
> == FAILED: Installation ended unsuccessfully (build directory: /home/mark.bessem/.local/easybuild/build/GCCcore/6.4.0/dummy-): build failed (first 300 chars): cmd " make -j 6 " exited with exit code 2 and output:
> make[1]: Entering directory `/home/mark.bessem/.local/easybuild/build/GCCcore/6.4.0/dummy-/gcc-6.4.0/stage1_obj'
> mkdir -p -- ./libiberty
> mkdir -p -- ./fixincludes
> mkdir -p -- ./lto-plugin
> mkdir -p -- ./intl
> mkdir -p -- ./gmp
> Configuring in ./libi
> == Results of the build can be found in the log file(s) /tmp/eb-XbF_uo/easybuild-GCCcore-6.4.0-20190416.110745.lWnfy.log
> ERROR: Build of /opt/ohpc/pub/libs/easybuild/3.8.1/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.8.1-py2.7.egg/easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0.eb failed (err: 'build failed (first 300 chars): cmd " make -j 6 " exited with exit code 2 and output:\nmake[1]: Entering directory `/home/mark.bessem/.local/easybuild/build/GCCcore/6.4.0/dummy-/gcc-6.4.0/stage1_obj\'\nmkdir -p -- ./libiberty\nmkdir -p -- ./fixincludes\nmkdir -p -- ./lto-plugin\nmkdir -p -- ./intl\nmkdir -p -- ./gmp\nConfiguring in ./libi')

[easybuild-GCCcore-6.4.0-20190416.110745.lWnfy.log](https://github.com/easybuilders/easybuild/files/3084345/easybuild-GCCcore-6.4.0-20190416.110745.lWnfy.log)
[easybuild-6MFqy4.log](https://github.com/easybuilders/easybuild/files/3084347/easybuild-6MFqy4.log)

**Comment by pescobar** [comment]
are you building in a network file system (nfs) ? If that's the case, can you try to build in a local filesystem using `eb --buildpath=/tmp/` ? (assuming that /tmp is a local file system)

Are you using latest version of easybuild? Do you experience the same problem if you try to build the `foss/2018b` toolchain?

**Comment by akesandgren** [comment]
The problem is likely caused by using s GCC 8.2 based system compiler which causes C++ problems with binutils 2.30

**Comment by HerderB** [comment]
Hello all,

Sorry for the late reply, been out a couple of days. Problem solved. It was the GCC version introduced by the OpenHPC as you suggested. When I unloaded the ohpc modules, gcc reverted to the system default and allowed me to install everything. Thanks for the help!
