### ISSUE TITLE
Offline bootstrap succeeds, but returns error unless EASYBUILD_BOOTSTRAP_SOURCEPATH is unset afterwards

### ISSUE THREAD

**Issue by runiq** [easybuilders/easybuild#519]
I was trying the procedure described [here](https://easybuild.readthedocs.io/en/latest/Installation.html#offline-bootstrapping-using-supplied-source-tarballs) which completed successfully. However, after loading the resulting `EasyBuild/3.9.2` module, every invocation with `eb` exits with the following error:

```
$ eb --help
ERROR: Failed to parse configuration options: 'Found 1 environment variable(s) that are prefixed with EASYBUILD but do not match valid option(s): EASYBUILD_BOOTSTRAP_SOURCEPATH'
```

The error goes away when I `unset EASYBUILD_BOOTSTRAP_SOURCEPATH`.

**Comment by runiq** [comment]
Sorry, wrong repository—reopened as https://github.com/easybuilders/easybuild-framework/issues/2934.

**Comment by boegel** [comment]
@runiq Wasn't use huge problem to have this here, since GitHub now has support to move issues to another repo, but fine. :)
