### ISSUE TITLE
matplotlib-3.0.0-foss-2018b-Python-3.6.6.eb crash

### ISSUE THREAD

**Issue by HerderB** [easybuilders/easybuild#529]
Hello all,

I haven't been able to install matplotlib-3.0.0-foss-2018b-Python-3.6.6.eb, which is a dependency for another package. See attached logs.
[easybuild-matplotlib-3.0.0-20190716.161327.DCmFK.log](https://github.com/easybuilders/easybuild/files/3405089/easybuild-matplotlib-3.0.0-20190716.161327.DCmFK.log)

On SLACK, Smoors suggested adding `buildopts = 'LDFLAGS="$LDFLAGS -L$EBROOTPYTHON/lib"'` to the .eb file. This did not help however, the error message remained the same (and I did try  `buildopts = 'LDFLAGS="$LDFLAGS -L $EBROOTPYTHON/lib"'` as well).

Using a different toolchain or version isn't an option seeing as this is a dependency for MultiQC.

**Comment by ocaisa** [comment]
I think @smoors is probably right, the issue is the location of the PYTHON directory in the link command (it is searching in the system directories first). Your placement in the easyconfig is off. though, I think you need to add
```
        'buildopts': "export LDFLAGS="$LDFLAGS -L $EBROOTPYTHON/lib" && ",
```
below https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.0-foss-2018b-Python-3.6.6.eb#L44 since the environment gets reset for every extension (meaning your redefinition of `LDFLAGS` gets reverted).

**Comment by ocaisa** [comment]
Original quoting was off in the line above...corrected

**Comment by ocaisa** [comment]
The issue could be that for some reason matplotlib is using `g++` to do the linking and this might be causing you to run into the issue @smoors mentioned on Slack (https://github.com/easybuilders/easybuild-easyconfigs/issues/5776). Is `LDSHARED` set in your environment?

Another option would be to use `LDSHARED` to override this behaviour and see what happens,
```
    (name, version, {
        'prebuildopts': 'export CPLUS_INCLUDE_PATH=$EBROOTFREETYPE/include/freetype2:${CPLUS_INCLUDE_PATH} && export LDSHARED="$CC -shared" && ',
        'preinstallopts': 'export CPLUS_INCLUDE_PATH=$EBROOTFREETYPE/include/freetype2:${CPLUS_INCLUDE_PATH} &&  export LDSHARED="$CC -shared" " &&',
        'source_urls': ['https://pypi.python.org/packages/source/m/matplotlib'],
        'checksums': ['b4e2333c98a7c2c1ff6eb930cd2b57d4b818de5437c5048802096b32f66e65f9'],
    }),
```

**Comment by HerderB** [comment]
LDSHARED is not set, running your previous suggestion now and I'll run your new one if that didn't work.

**Comment by HerderB** [comment]
> Ok, `buildopts` is wrong, let's try that again since I definitely see `CPLUS_INCLUDE_PATH` being set:
> 
> ```
>     (name, version, {
>         'prebuildopts': 'export CPLUS_INCLUDE_PATH=$EBROOTFREETYPE/include/freetype2:${CPLUS_INCLUDE_PATH} && export LDFLAGS="$LDFLAGS -L $EBROOTPYTHON/lib" && ',
>         'preinstallopts': 'export CPLUS_INCLUDE_PATH=$EBROOTFREETYPE/include/freetype2:${CPLUS_INCLUDE_PATH} &&  export LDFLAGS="$LDFLAGS -L $EBROOTPYTHON/lib" &&',
>         'source_urls': ['https://pypi.python.org/packages/source/m/matplotlib'],
>         'checksums': ['b4e2333c98a7c2c1ff6eb930cd2b57d4b818de5437c5048802096b32f66e65f9'],
>     }),
> ```

This one worked! Thanks!

**Comment by ocaisa** [comment]
I'll move this over to the easyconfigs repo in case someone runs into this in the future.
