### ISSUE TITLE
Module conflicts in EasyBuild/2.9.0 

### ISSUE THREAD

**Issue by ponomarevsy** [easybuilders/easybuild#550]
I am observing a very strange behavior, in which a specific module loads fine on one node, but complains about module conflicts on the other. Both nodes are identical but I suspect there might be slight differences in the EB configuration files. I made sure the environment-modules/3.2.10/init/ folder is identical on both nodes. Applications are kept on a GPFS mounted share accessible to both nodes. I do not completely understand this, but here is what I have:
```
user@node1: module load rufus/1.0-goolf-1.7.20
GCC/4.9.2(13):ERROR:150: Module 'GCC/4.9.2' conflicts with the currently loaded module(s) 'GCC/4.8.4'
GCC/4.9.2(13):ERROR:102: Tcl command execution failed: conflict GCC

To execute RUFUS run: $EBROOTRUFUS/runRufus.sh 
```
```
user@node2: module load rufus/1.0-goolf-1.7.20
To execute RUFUS run: $EBROOTRUFUS/runRufus.sh
```
And the module file is:
```
#%Module
proc ModulesHelp { } {
    puts stderr { K-mer based variant detection. - Homepage: https://github.com/jandrewrfarrell/RUFUS
    }
}

module-whatis {Description: K-mer based variant detection. - Homepage: https://github.com/jandrewrfarrell/RUFUS}

set root /path/software/rufus/1.0-goolf-1.7.20

conflict rufus

module rm GCC/4.9.2

if { ![ is-loaded goolf/1.7.20 ] } {
    module load goolf/1.7.20
}

if { ![ is-loaded htslib/1.9-goolf-1.7.20 ] } {
    module load htslib/1.9-goolf-1.7.20
}

if { ![ is-loaded samtools/1.9-goolf-1.7.20 ] } {
    module load samtools/1.9-goolf-1.7.20
}

if { [ is-loaded GCC/4.8.4 ] } {
    module rm GCC/4.8.4
    module load GCC/4.9.2
}
#module switch GCC/4.8.4 GCC/4.9.2

prepend-path	PATH		$root/bin
setenv	EBROOTRUFUS		"$root"
setenv	EBVERSIONRUFUS		"1.0"
setenv	EBDEVELRUFUS		"$root/easybuild/rufus-1.0-goolf-1.7.20-easybuild-devel"

prepend-path	PATH		$root

if { [ module-info mode load ] } {
    puts stderr "To execute RUFUS run: \$EBROOTRUFUS/runRufus.sh"
}

# Built with EasyBuild version 2.9.0
```
Since rufus requires GCC/4.9.2 compiler, but it also requires samtools compiled under GCC/4.8.4, I am unloading GCC/4.9.2, then loading samtools (it comes with GCC/4.8.4), then unloading GCC/4.8.4 and loading GCC/4.9.2. It is a bit tricky, but it works fine on node2 but not node1! How so? I do NOT completely understand since both nodes are identical.

Please let me know if you have any clues. Thank you!

**Comment by boegel** [comment]
This is more of a modules tool problem rather than an actual EasyBuild problem... EasyBuild generated the module file, but it seems like it was manually changed afterwards?

That being said, I agree this is a weird problem. Maybe something on `node1` is different and it affects the order in which statements are being evaluated in the module file?

Maybe @xdelaruelle (as current maintainers of the Tcl-based modules tool) has a better idea?

To clarify: the `load goolf/1.7.20` implies a load of `GCC/4.9.2` in this setup, is that right @ponomarevsy?

**Comment by ponomarevsy** [comment]
Thanks for your feedback, @boegel! I used a template EB file to install rufus archive. I was then, fiddling with the module file that was created, since a user noticed that is was not working as expected on node1.

Module goolf/1.7.20 comes with of GCC/4.8.4 compiler, unfortunately. The main idea of this exercise was to avoid re-compiling Samtools and Htslib modules with GCC/4.9.2 (RUFUS requires GCC/4.9.2). But now I am thinking, should I give up and re-compile?

**Comment by boegel** [comment]
@ponomarevsy In the long run, that's probably the best option. By swapping out `GCC/4.8.4` with `GCC/4.9.2`, you may actually be (subtly) breaking SAMtools and HTSlib without noticing...

**Comment by xdelaruelle** [comment]
@ponomarevsy My guess would be that the content of the modulefiles implied here or the list of loaded modules prior `rufus/1.0-goolf-1.7.20` load differ between the 2 nodes

Could you ensure:
* the content of your modulefiles are the same on the two nodes
* `module list` returns you the same result on both nodes prior loading `rufus/1.0-goolf-1.7.20`

**Comment by ponomarevsy** [comment]
Thanks, @xdelaruelle! It turns out we have "env-modules-3.2.10-136_cm8.0.x86_64" installed on some nodes, while other nodes have older "env-modules-3.2.10-132_cm8.0.x86_64" package installed. RUFUS sort of works with the newer package but not with the older one. Appreciate your help, @boegel & @xdelaruelle!
