### ISSUE TITLE
Use print() function in both Python 2 and Python 3

### ISSUE THREAD

**Issue by cclauss** [easybuilders/easybuild#568]
flake8 testing of https://github.com/easybuilders/easybuild on Python 3.8.0

__flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./docs/scripts/gen_easyblocks_docs.py:69:11: E999 SyntaxError: invalid syntax
    print '%s updated' % so.options.out_file
          ^
./docs/scripts/gen_api_docs.py:52:7: E999 SyntaxError: invalid syntax
print "$ %s" % cmd
      ^
2     E999 SyntaxError: invalid syntax
2
```

**Comment by GhayoorUlHaq** [comment]
For Python 3.x,  print function without round brackets will not work that's why you're having syntax. It's only valid for python 2.x you have to do like this:

**Comment by cclauss** [comment]
The directive `from __future__ import print_function` makes both Python 2 and Python 3 behave identically.
