### ISSUE TITLE
ERROR: Incompatible Python version: 3.6.8 (should be Python 2 >= 2.6)

### ISSUE THREAD

**Issue by pgirardgerad** [easybuilders/easybuild#577]
Hello,
  The bootstrap_eb.py script seems to be confused about versions, I called it with 
`python3 bootstrap_eb.py $EASYBUILD_PREFIX`

and it seems to think this is python 2.

```
ERROR: Incompatible Python version: 3.6.8 (should be Python 2 >= 2.6)
Please try again using 'python2 bootstrap_eb.py <prefix>'
```

The OS I'm trying this on is a RHEL8 variant.
Red Hat Enterprise Linux release 8.1 (Ootpa)

Python 3 (/usr/bin/python3)
python3-urllib3
Lmod 8.1.17

**Comment by pgirardgerad** [comment]
I should've looked at the code before posting but there's this test in the script that causes the program to exit.
`if sys.version_info[0] != 2 or sys.version_info[1] < 6:`

so it seems to specifically check that it is python 2 and not python 3. 
On this page https://easybuild.readthedocs.io/en/latest/Installation.html it mentions being compatible with python3 which is why I didn't even try python2.

**Comment by boegel** [comment]
@pgirardgerad EasyBuild 4.0 & newer is compatible with Python 3.5+ (as well as Python 2.6 & 2.7), but the bootstrap script is not compatible with Python 3 yet (see https://github.com/easybuilders/easybuild-framework/pull/3028).

So, you have a couple of options:

1) install EasyBuild using the bootstrap script using `python2`, as suggested

2) install EasyBuild with `pip3 install easybuild` (or another Python installation tool using Python 3)

3) download the source tarballs for the `easybuild-*` Python packages (either from PyPI or GitHub), unpacked them, updating `$PYTHONPATH` to all three (+ `$PATH` for the `eb` command in `easybuild-framework`)

If you use option 2 or 3 you can consider doing the installation in a temporary location, and then using `eb --install-latest-eb-release --prefix ...` to do the bootstrap in the final installation location yourself.

The bootstrap script is mostly convenient for people not familiar with installing Python packages, but EasyBuild installs just fine in the usual way too like any other Python software.
If you install EasyBuild with EasyBuild (like the bootstrap script or `eb --install-latest-eb-release` does), you also get an environment module file so you can "activate" the EasyBuild installation using "`module load EasyBuild`).

**Comment by pgirardgerad** [comment]
Thanks for the information.

Option 1 doesn't work because libbcurl2 is not available on the system.
I tried option 2 and I was able to complete the installation.

**Comment by boegel** [comment]
@pgirardgerad In that case this issue can be closed?

**Comment by pgirardgerad** [comment]
I have another issue getting it to work but we can close this one and I'll open another if needed when I have more time to look at what's going on.
