### ISSUE TITLE
Add documentation for self.cfg structure and content in EasyBlocks?

### ISSUE THREAD

**Issue by kelseymh** [easybuilders/easybuild#618]
I was recently working on a couple of different EasyBlock modifications ([EasyBlocks PR #2010](https://github.com/easybuilders/easybuild-easyblocks/pull/2010) and [EasyBlocks Issue #2024](https://github.com/easybuilders/easybuild-easyblocks/issues/2024) and had a difficult time understanding how to access the information from an EasyConfig within the EasyBlock I was writing or modifying.

I was able to figure out what to do, by searching GitHub, looking at various other EasyBlocks, and eventually tracing my way up through the generic EasyBlocks to easyblock.py.

But I think it might make it easier for othrs if the existence, and expected content, of `self.cfg` was documented in `Implementing-easyblocks.rst`.  The individual dictionary entries (like `self.cfg['sources']`) probably also need to be documented, and/or cross-referenced back to their definitions in the EasyConfig docs.  

I will have a go at doing this myself, but I am confident that what I write will be incomplete: just from reading `easyblock.py`, it seems like the structure can be pretty multilayered.

**Comment by kelseymh** [comment]
I'm implementing this as part of PR #617 , and will update the title and description there.

**Comment by kelseymh** [comment]
@boegel has added some [comments](https://github.com/easybuilders/easybuild/pull/617/files#r449669160) to the changes that got merged in PR #617 .  I'll make the requested changes via a new PR.

**Comment by boegel** [comment]
Closing this now #617 and #634 are merged... Thanks @kelseymh!
