### ISSUE TITLE
problem install python 3.7.2 on centos 8 xml.etree.ElementTree.ParseError

### ISSUE THREAD

**Issue by alchemroz** [easybuilders/easybuild#622]
Hello,
         I installed successfully easybuild 4.2.0 on a centos 8 with pip 3.6. Everything went smooth until the installation of

eb Python-3.7.2-GCCcore-8.2.0.eb --robot

I attached the log 
[easybuild-vdqc5b6i.log](https://github.com/easybuilders/easybuild/files/4594100/easybuild-vdqc5b6i.log)

Thanks for the help

**Comment by ocaisa** [comment]
Answered in #621, closing
