### ISSUE TITLE
Problem with USEARCH  configuration file

### ISSUE THREAD

**Issue by zamanzad** [easybuilders/easybuild#658]
Hi,
I have got a problem for installing USEARCH software in our local server using Easybuild. The server actually mirrors the configuration files that are available in easybuild github.
if we do  eb USEARCH-5.2.236-6.1.544-i86linux32.eb --fetch we will get the following error:
FAILED: Installation ended unsuccessfully    Couldn't find file usearch5.2.236_i86linux32 anywhere, and downloading it didn't work either... Paths attempted (in order): /cluster/software/EasyBuild/4.3.1/easybuild/easyconfigs/u/USEARCH/u/USEARCH/usearch5.2.236_i86linux32, 

I could see here there are "u/USEARCH/u/USEARCH/" so double folder for USERACH, was wondering if this a bug or something else that we need to be aware of. Many thanks for your help and guidance.
Regards,
Fatemeh

**Comment by bartoldeman** [comment]
The double path is normal and that output is truncated. You need to look at the log file to see the full list of attempted locations.

What I see is this:
```
Couldn't find file usearch5.2.236_i86linux32 anywhere, and downloading it didn't work either... Paths attempted (in order): /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/u/USEARCH/u/USEARCH/usearch5.2.236_i86linux32, /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/u/USEARCH/USEARCH/usearch5.2.236_i86linux32, /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/u/USEARCH/usearch5.2.236_i86linux32, /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/u/USEARCH/usearch5.2.236_i86linux32, /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/USEARCH/usearch5.2.236_i86linux32, /cvmfs/soft.computecanada.ca/easybuild/easyconfigs/usearch5.2.236_i86linux32, /home/oldeman/.local/easybuild/ebfiles_repo/2017/u/USEARCH/usearch5.2.236_i86linux32, /home/oldeman/.local/easybuild/ebfiles_repo/2017/USEARCH/usearch5.2.236_i86linux32, /home/oldeman/.local/easybuild/ebfiles_repo/2017/usearch5.2.236_i86linux32, /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2017/u/USEARCH/usearch5.2.236_i86linux32, /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2017/USEARCH/usearch5.2.236_i86linux32, /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2017/usearch5.2.236_i86linux32, /cvmfs/soft.computecanada.ca/easybuild/site-packages/easybuild-easyconfigs/easybuild/easyconfigs/u/USEARCH/usearch5.2.236_i86linux32, /cvmfs/soft.computecanada.ca/easybuild/site-packages/easybuild-easyconfigs/easybuild/easyconfigs/USEARCH/usearch5.2.236_i86linux32, /cvmfs/soft.computecanada.ca/easybuild/site-packages/easybuild-easyconfigs/easybuild/easyconfigs/usearch5.2.236_i86linux32, /home/oldeman/.local/easybuild/sources/u/USEARCH/usearch5.2.236_i86linux32, /home/oldeman/.local/easybuild/sources/USEARCH/usearch5.2.236_i86linux32, /home/oldeman/.local/easybuild/sources/usearch5.2.236_i86linux32  (at easybuild/site-packages/easybuild-framework/easybuild/framework/easyblock.py:816 in obtain_file)
```

what you'd need to do is to download USEARCH manually to one of the locations mentioned in the log file via http://www.drive5.com/usearch/download.html -- however if you install in a shared location on a cluster you will need to change the permissions of the binaries afterwards as per the license (http://www.drive5.com/usearch/download_academic_site.html)
