### ISSUE TITLE
problem with token eb --install-github-token 

### ISSUE THREAD

**Issue by aahameed** [easybuilders/easybuild#670]
I am using easy build latest ( 4 ) with centos 7,  everything in the installation is good,
 then I did  eb --install-github-token and I got the token installed 
 but when I try to run the GitHub token check command  I got FAIL in user name and token, I don't know why.

**Comment by ocaisa** [comment]
Can you run `eb --check-github --github-user=YOUR-GITHUB-ID` and post the results?

**Comment by aahameed** [comment]
/usr/lib/python2.7/site-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.utils import int_from_bytes
== temporary log file in case of crash /tmp/eb-bkMAb5/easybuild-bgVo94.log

Checking status of GitHub integration...

Making sure we're online...OK

* GitHub user...aahameed => OK
* GitHub token...(no token found) => FAIL
* git command...OK ("git version 1.8.3.1; ")
* GitPython module...OK (GitPython version 1.0.1)

**Comment by ocaisa** [comment]
Have you got the keyring package installed? See, https://docs.easybuild.io/en/develop/Integration_with_GitHub.html?highlight=python#github-requirements
```
pip install 'keyring<19.0'
```

**Comment by aahameed** [comment]
i reinstall it and i got 

usr/lib/python2.7/site-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.utils import int_from_bytes
== temporary log file in case of crash /tmp/eb-u9cN8v/easybuild-CV8A2b.log

Checking status of GitHub integration...

Making sure we're online...OK

* GitHub user...aahameed => OK
Please enter password for encrypted keyring: * GitHub token...
760..3c0 (len: 40) => OK (validated)
* git command...OK ("git version 1.8.3.1; ")
* GitPython module...OK (GitPython version 1.0.1)
* push access to aahameed/easybuild-easyconfigs repo @ GitHub...FAIL (unexpected exception: 'Checking out branch \'master\' from git@github.com:aahameed/easybuild-easyconfigs.git failed: "Failed to fetch branch \'master\' from git@github.com:aahameed/easybuild-easyconfigs.git: \'Error when fetching: fatal: Could not read from remote repository.\' returned with exit code 2"')
* creating gists...OK
* location to Git working dirs... not found (suboptimal)

One or more checks FAILed, GitHub configuration not fully complete!
See http://easybuild.readthedocs.org/en/latest/Integration_with_GitHub.html#configuration for help.

Status of GitHub integration:
* --from-pr: OK
* --new-pr: not supported
* --review-pr: OK
* --update-pr: not supported
* --upload-test-report: OK



but when i run 

python -m test.framework.suite  


i got  

/usr/lib/python2.7/site-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.utils import int_from_bytes
F.F............F..^[[B.........Skipping test_copy_ec_from_pr, no GitHub token available?
......Ferr: 'Failed to process easyconfig /home/modules/easybuild/software/EasyBuild/4.3.2/lib/python2.7/site-packages/test/framework/easyconfigs/test_ecs/g/gzip/gzip-1.5-foss-2018a.eb: Failed to process easyconfig /home/modules/easybuild/software/EasyBuild/4.3.2/lib/python2.7/site-packages/test/framework/easyconfigs/test_ecs/f/foss/foss-2018a.eb: Failed to process easyconfig /home/modules/easybuild/software/EasyBuild/4.3.2/lib/python2.7/site-packages/test/framework/easyconfigs/test_ecs/o/OpenMPI/OpenMPI-2.1.2-GCC-6.4.0-2.28.eb: Toolchain GCC not found, available toolchains: GCCcore,system'
Eerr: 'Failed to process easyconfig /home/modules/easybuild/software/EasyBuild/4.3.2/lib/python2.7/site-packages/test/framework/easyconfigs/test_ecs/g/gzip/gzip-1.5-foss-2018a.eb: Failed to process easyconfig /home/modules/easybuild/software/EasyBuild/4.3.2/lib/python2.7/site-packages/test/framework/easyconfigs/test_ecs/f/foss/foss-2018a.eb: Failed to process easyconfig /home/modules/easybuild/software/EasyBuild/4.3.2/lib/python2.7/site-packages/test/framework/easyconfigs/test_ecs/o/OpenMPI/OpenMPI-2.1.2-GCC-6.4.0-2.28.eb: Toolchain GCC not found, available toolchains: GCCcore,system'
EEE.E...Skipping test_empty_pr, no GitHub token available?
.F..F.err: 'Failed to process easyconfig /home/modules/easybuild/software/EasyBuild/4.3.2/lib/python2.7/site-packages/test/framework/easyconfigs/test_ecs/o/OpenMPI/OpenMPI-2.1.2-GCC-6.4.0-2.28.eb: Toolchain GCC not found, available toolchains: GCCcore,system'
E...Skipping test_from_pr, no GitHub token available?
.Skipping test_from_pr, no GitHub token available?
.Skipping test_from_pr_token_log, no GitHub token available?
.Skipping test_from_pr_x, no GitHub token available?
......err: 'Failed to process easyconfig /home/modules/easybuild/software/EasyBuild/4.3.2/lib/python2.7/site-packages/test/framework/easyconfigs/test_ecs/o/OpenMPI/OpenMPI-2.1.2-GCC-6.4.0-2.28.eb: Toolchain GCC not found, available toolchains: GCCcore,system'
EF.....F.....EFSkipping test_merge_pr, no GitHub token available?
.EE..Skipping test_create_branch_github, no GitHub token available?
.Skipping test_new_pr_delete, no GitHub token available?
.Skipping test_new_pr_dependencies, no GitHub token available?
.Skipping test_new_pr_from_branch, no GitHub token available?
.Skipping test_new_pr_python, no GitHub token available?
.Skipping test_new_update_pr, no GitHub token available?
......Skipping test_preview_pr, no GitHub token available?
...err: 'gompi'

**Comment by ocaisa** [comment]
Have you forked the repositories on GitHub? Make sure that you go through all of the steps in http://easybuild.readthedocs.org/en/latest/Integration_with_GitHub.html#configuration

**Comment by boegel** [comment]
@aahameed Is this still a problem, or did you manage to get it working?

**Comment by aahameed** [comment]
Yeah I am still testing and have a lot of problems regardless GCC core toolchain

**Comment by aahameed** [comment]
i am still got this error 

Checking status of GitHub integration...

Making sure we're online...OK

* GitHub user...aahameed => OK
* GitHub token...d31..012 (len: 40) => OK (validated)
* git command...OK ("git version 1.8.3.1; ")
* GitPython module...OK (GitPython version 2.1.15)
* push access to aahameed/easybuild-easyconfigs repo @ GitHub...== fetching branch 'master' from git@github.com:aahameed/easybuild-easyconfigs.git...
FAIL (unexpected exception: 'Checking out branch \'master\' from git@github.com:aahameed/easybuild-easyconfigs.git failed: "Failed to fetch branch \'master\' from git@github.com:aahameed/easybuild-easyconfigs.git: Cmd(\'git\') failed due to: exit code(128)\\n  cmdline: git fetch -v pr_target_account_aahameed_lSwoT\\n  stderr: \'fatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\'"')
* creating gists...OK
* location to Git working dirs... OK (/home/modules/shared/gitdir)

One or more checks FAILed, GitHub configuration not fully complete!
See http://easybuild.readthedocs.org/en/latest/Integration_with_GitHub.html#configuration for help.

Status of GitHub integration:
* --from-pr: OK
* --new-pr: not supported
* --review-pr: OK
* --update-pr: not supported
* --upload-test-report: OK

**Comment by aahameed** [comment]
Any Solution?

**Comment by ocaisa** [comment]
Your git version is very old (2013), perhaps it is an incompatibility with GitPython?

**Comment by ocaisa** [comment]
I am out of ideas, the only thing I can think of is that your GitHub token does not have the right permissions. Try creating a new one (again) with the permissions as described in https://docs.easybuild.io/en/latest/Integration_with_GitHub.html#github-token (you will need to use the `--force` option to overwrite the existing token. Make sure that the new token is being used that the reported  characters in the output of `--check-github` match the key you added

**Comment by ocaisa** [comment]
I think I may have ran into this problem myself. One of the requirements for GitHub integration is

* SSH public key registered on GitHub (see https://github.com/settings/keys)

Do you have an ssh key registered on GitHub accessible to the machine where you are running these tests?

**Comment by ocaisa** [comment]
Nothing on this for quite a while, closing
