### ISSUE TITLE
Problem with proxy

### ISSUE THREAD

**Issue by javialra97** [easybuilders/easybuild#679]
Hello 
I have installed EasyBuild v3.9.4 and I have a trouble trying to work behind a proxy,  I don't know how configure proxy with the python library urllib2.
This is the log

`eb --installpath=/opt/ohpc/pub/apps AutoDock_Vina-1.1.2_linux_x86.eb -r
ERROR: Build of /opt/ohpc/pub/libs/easybuild/3.9.4/software/EasyBuild/3.9.4/lib/python2.7/site-packages/easybuild_easyconfigs-3.9.4-py2.7.egg/easybuild/easyconfigs/a/AutoDock_Vina/AutoDock_Vina-1.1.2_linux_x86.eb failed (err: "build failed (first 300 chars): Couldn't find file autodock_vina_1_1_2_linux_x86.tgz anywhere, and downloading it didn't work either... Paths attempted (in order): /opt/ohpc/pub/libs/easybuild/3.9.4/software/EasyBuild/3.9.4/lib/python2.7/site-packages/easybuild_easyconfigs-3.9.4-py2.7.egg/easybuild/easyconfigs/a/AutoDock_Vina/a/Au")`

Thanks

**Comment by ocaisa** [comment]
Did you try the [envionment variable mentioned in the docs](https://docs.python.org/2/library/urllib.html#urllib.urlopen)?
```
% http_proxy="http://www.someproxy.com:3128"
% export http_proxy
% python
```

**Comment by javialra97** [comment]
Hi,
That enviorement variable are declared in my .bashrc, nevertheless I tried and did not work. 
I also have a doubt about the command python because with it a python terminal is opened, should I use then eb ....

**Comment by ocaisa** [comment]
I think you might be out of luck, I also see in the docs:
```
Currently urllib.request does not support fetching of https locations through a proxy.
```

**Comment by ocaisa** [comment]
Hmm, I'm not sure that is true. I did find something for `requests` that is worth trying:
```
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"

$ python
>>> import requests
>>> requests.get('http://example.org')
```
If that works for the test, then it should also work for EasyBuild

**Comment by javialra97** [comment]
But I should call the command 
`eb easybuild.eb -r`
in the python prompt??

**Comment by ocaisa** [comment]
No, first you need to check if the proxy is working at all with python, if it is then you can call `eb easybuild.eb -r` from the shell and see if that works.

**Comment by javialra97** [comment]
Hi, the proxy of my university also have user and password and should be declared in the same export and not as a differente variable, so I export in this way export http_proxy=http://user:pass@proxy:port, and I obtein a [200] response in python so that means that it works!!!!! yeah, but when I tried with eb it something intermittent, sometimes work and other no, and it's not a problem of the proxy of the university because in all the time in python I always obtein the same 200 response, so, you have any idea??

**Comment by ocaisa** [comment]
You also need to set the https proxy (I think):
```
https_proxy=http://user:pass@proxy:port
```
and the https port you need is probably different (like in my comment above from yesterday)

**Comment by javialra97** [comment]
it is also declared in the .bashrc
and in my case is the same port

**Comment by ocaisa** [comment]
And the following is successful:
```
$ python
>>> import requests
>>> requests.get('https://example.org')
```
(note the https)

If so, I am out of ideas. Can you say what URLs are failing?

**Comment by javialra97** [comment]
right now i have this problem
urllib3.exceptions.LocationParseError: Failed to parse: 10.6.100.71::3128
but a few minutes ago it wasn't
I don't know why it says urllib3 because the prompt is the python 2.7

**Comment by javialra97** [comment]
I don't know why but It's working right now so I suppose that some network admin should be doing something
