### ISSUE TITLE
Command line flag issue

### ISSUE THREAD

**Issue by ebgregory** [easybuilders/easybuild#68]
I notice that if I forget to include a value after --deprecated , eb (v 1.16.1) seems to ignore flags that come afterwards. E.g.:

eb --deprecated=2.0 --dry-run  popt-1.16.eb
gives me a dry run report, as it should.

eb --dry-run  --deprecated popt-1.16.eb 
complains that --deprecated is used improperly and fails, as it should.

But:
eb --deprecated --dry-run  popt-1.16.eb
installs popt fully and 
eb --deprecated --hidden popt-1.16.eb
installs popt, but does not install it as hidden.

Of course Im using the flag incorrectly.

-Eric

**Comment by boegel** [comment]
@ebgregory: that's pretty scary... in the `eb --deprecated --dry-run` case, it should complain that a required value is missing.

@stdweird: how does generaloption handle this? Seems like it's considering `--dry-run` as a value for `--deprecated`?

**Comment by migueldiascosta** [comment]
fixed in https://github.com/hpcugent/vsc-base/pull/199 (later ingested into easybuild.base), now this errors out with e.g. `eb: error: Value '--dry-run' is also a valid option. Use '--deprecated=--dry-run' if the value is correct.`
