### ISSUE TITLE
eb fails to download sources

### ISSUE THREAD

**Issue by YensyGomez** [easybuilders/easybuild#683]
Hi everyone :).

We've founded when I try to install "eb intel-compilers-2021.1.2.eb -D"  it shows some dependencies to install before, but for example, one of them is: eb GCCcore-10.2.0.eb --fetch -d, and I get this: 
`eb GCCcore-10.2.0.eb --fetch -d`

`== Temporary log file in case of crash /sNow/easybuild/tmp/easybuild-IAUF8l.log
== found valid index for /sNow/easybuild/software/EasyBuild/4.3.3/easybuild/easyconfigs, so using it...
== processing EasyBuild easyconfig /home/snow/eb/GCCcore-10.2.0.eb
== building and installing GCCcore/10.2.0...
== fetching files...`

error: 
`== FAILED: Installation ended unsuccessfully (build directory: /sNow/easybuild/centos/7.4.1708/Skylake/build/GCCcore/10.2.0/system-system): build failed (first 300 chars): Couldn't find file mpfr-4.1.0.tar.bz2 anywhere, and downloading it didn't work either... Paths attempted (in order): /home/snow/eb/g/GCCcore/mpfr-4.1.0.tar.bz2, /home/snow/eb/GCCcore/mpfr-4.1.0.tar.bz2, /home/snow/eb/mpfr-4.1.0.tar.bz2, /sNow/easybuild/software/EasyBuild/4.3.3/easybuild/easyconfigs/ (took 21 sec)
== Results of the build can be found in the log file(s) /sNow/easybuild/tmp/easybuild-GCCcore-10.2.0-20210319.103648.pJtBu.log
ERROR: Build of /home/snow/eb/GCCcore-10.2.0.eb failed (err: "build failed (first 300 chars): Couldn't find file mpfr-4.1.0.tar.bz2 anywhere, and downloading it didn't work either... Paths attempted (in order): /home/snow/eb/g/GCCcore/mpfr-4.1.0.tar.bz2, /home/snow/eb/GCCcore/mpfr-4.1.0.tar.bz2, /home/snow/eb/mpfr-4.1.0.tar.bz2, /sNow/easybuild/software/EasyBuild/4.3.3/easybuild/easyconfigs/")`

We've tried to check the source downloading with wget and curl  commands, but we think the sources are broken:
with curl:

`curl -o mpfr-4.1.0.tar.bz2 https://ftpmirror.gnu.org/gnu/mpfr/mpfr-4.1.0.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0`

with wget:
`wget  https://ftpmirror.gnu.org/gnu/mpfr/mpfr-4.1.0.tar.bz2
--2021-03-19 10:40:57--  https://ftpmirror.gnu.org/gnu/gmp/gmp-6.2.0.tar.bz2
Resolving ftpmirror.gnu.org (ftpmirror.gnu.org)... 209.51.188.200, 2001:470:142:5::200
Connecting to ftpmirror.gnu.org (ftpmirror.gnu.org)|209.51.188.200|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily`

but if we use this path `https://ftp.rediris.es/mirror/GNU/mpfr/mpfr-4.1.0.tar.bz2` with wget:
`wget https://ftp.rediris.es/mirror/GNU/mpfr/mpfr-4.1.0.tar.bz2
--2021-03-19 10:48:57--  https://ftp.rediris.es/mirror/GNU/mpfr/mpfr-4.1.0.tar.bz2
Resolving ftp.rediris.es (ftp.rediris.es)... 130.206.13.2, 2001:720:418:cafd::2
Connecting to ftp.rediris.es (ftp.rediris.es)|130.206.13.2|:443... connected.
HTTP request sent, awaiting response... 200 OK`

with curl: 
`curl -o mpfr-4.1.0.tar.bz2 https://ftp.rediris.es/mirror/GNU/mpfr/mpfr-4.1.0.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1706k  100 1706k    0     0  3234k      0 --:--:-- --:--:-- --:--:-- 3231k`

We think the problem is with the path inside the recipe. Could you help me with it, because eb intel-compilers-2021.1.2.eb -D has too many dependencies to install, and now all of them have the same problem with the sources.

We saw this guy had a similar problem [https://github.com/easybuilders/easybuild/issues/115](url), we tried the same solution but it didn't work.

We open this issue to get a solution about our problem. Thank so much.

Best regards 
Helena

**Comment by akesandgren** [comment]
I can't see a problem downloading
https://ftpmirror.gnu.org/gnu/mpfr/mpfr-4.1.0.tar.bz2

You may just have been unlucky. Remove any downloaded version of it and
try again with a normal eb build of GCCcore

On 3/19/21 11:04 AM, YensyGomez wrote:
> Hi everyone :).
> 
> We've founded when I try to install "eb intel-compilers-2021.1.2.eb -D"
> it shows some dependencies to install before, but for example, one of
> them is: eb GCCcore-10.2.0.eb --fetch -d, and I get this:
> |eb GCCcore-10.2.0.eb --fetch -d|
> 
> |== Temporary log file in case of crash
> /sNow/easybuild/tmp/easybuild-IAUF8l.log == found valid index for
> /sNow/easybuild/software/EasyBuild/4.3.3/easybuild/easyconfigs, so using
> it... == processing EasyBuild easyconfig /home/snow/eb/GCCcore-10.2.0.eb
> == building and installing GCCcore/10.2.0... == fetching files...|
> 
> error:
> |== FAILED: Installation ended unsuccessfully (build directory:
> /sNow/easybuild/centos/7.4.1708/Skylake/build/GCCcore/10.2.0/system-system):
> build failed (first 300 chars): Couldn't find file mpfr-4.1.0.tar.bz2
> anywhere, and downloading it didn't work either... Paths attempted (in
> order): /home/snow/eb/g/GCCcore/mpfr-4.1.0.tar.bz2,
> /home/snow/eb/GCCcore/mpfr-4.1.0.tar.bz2,
> /home/snow/eb/mpfr-4.1.0.tar.bz2,
> /sNow/easybuild/software/EasyBuild/4.3.3/easybuild/easyconfigs/ (took 21
> sec) == Results of the build can be found in the log file(s)
> /sNow/easybuild/tmp/easybuild-GCCcore-10.2.0-20210319.103648.pJtBu.log
> ERROR: Build of /home/snow/eb/GCCcore-10.2.0.eb failed (err: "build
> failed (first 300 chars): Couldn't find file mpfr-4.1.0.tar.bz2
> anywhere, and downloading it didn't work either... Paths attempted (in
> order): /home/snow/eb/g/GCCcore/mpfr-4.1.0.tar.bz2,
> /home/snow/eb/GCCcore/mpfr-4.1.0.tar.bz2,
> /home/snow/eb/mpfr-4.1.0.tar.bz2,
> /sNow/easybuild/software/EasyBuild/4.3.3/easybuild/easyconfigs/")|
> 
> We've tried to check the source downloading with wget and curl commands,
> but we think the sources are broken:
> with curl:

-- 
Ake Sandgren, HPC2N, Umea University, S-90187 Umea, Sweden
Internet: ***@***.***   Phone: +46 90 7866134 Fax: +46 90-580 14
Mobile: +46 70 7716134 WWW: http://www.hpc2n.umu.se

**Comment by boegel** [comment]
EasyBuild can't guarantee that downloads will always go smoothly, especially if there are problems upstream.

I'll close this issue and assume that a retry fixed the problem. Note that you can force a re-download using `eb --force-download`
