### ISSUE TITLE
EasyBuild/4.3.3 creates module files with "-rw-r-----" permissions

### ISSUE THREAD

**Issue by ponomarevsy** [easybuilders/easybuild#688]
Looks like the new EasyBuild/4.3.3 creates module files with "-rw-r-----" (640) permissions instead of the default "-rw-rw-r--" (664) permissions. This causes 'module av' command to fail:
```
$ module av
utility.c(2245):ERROR:50: Cannot open file '/modules/all/Autoconf/2.69-GCCcore-10.2.0' for 'reading'
utility.c(2245):ERROR:50: Cannot open file '/modules/all/Perl/5.32.0-GCCcore-10.2.0' for 'reading'
utility.c(2245):ERROR:50: Cannot open file '/modules/all/libreadline/8.0-GCCcore-10.2.0' for 'reading'
utility.c(2245):ERROR:50: Cannot open file '/modules/all/expat/2.2.9-GCCcore-10.2.0' for 'reading'
utility.c(2245):ERROR:50: Cannot open file '/modules/all/gettext/0.21' for 'reading'
utility.c(2245):ERROR:50: Cannot open file '/modules/all/Bison/3.5.3' for 'reading'
```
Is this a new security feature or a bug? How can I make EasyBuild/4.3.3 write module files with 664 permissions?

Please let me know. Thank you!

**Comment by boegel** [comment]
@ponomarevsy This is not normal behavior, by default you should be getting 664 permissions on module files...

How did you configure EasyBuild? Please share the output of `eb --show-config`.

In addition, what's the default umask on your system (see output of running `umask` as a command)?

**Comment by ponomarevsy** [comment]
Thanks for your reply, @boegel. This is what I get:
```
» module list                                                                                                                       
Currently Loaded Modulefiles:
  1) EasyBuild/4.3.3   2) uge/8.6.15

» eb --show-config                                                                                                                  
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath      (F) = /sysapps/cluster/build
containerpath  (F) = /sysapps/cluster/containers
installpath    (F) = /sysapps/cluster
module-syntax  (C) = Tcl
modules-tool   (C) = EnvironmentModulesC
packagepath    (F) = /sysapps/cluster/packages
prefix         (F) = /sysapps/cluster
repositorypath (F) = /sysapps/cluster/ebfiles_repo
robot-paths    (D) = /sysapps/cluster/software/EasyBuild/4.3.3/easybuild/easyconfigs
sourcepath     (F) = /sysapps/cluster/sources
                                                                                                                                   
» umask                                                                                                                             
002
```

**Comment by ocaisa** [comment]
Your umask looks ok and you don't seem to have anything in your settings that would affect this. Did you perform the installations or was it someone else? If you reinstall something (using `--force`) do you still get the same permissions on the resulting module file?

**Comment by ponomarevsy** [comment]
Yes, I did the install of the new EB module. I was loading and purging that EB module several times that day and it may have screwed something up in the EB environment. Last time I used EB, it created a new modulefile with "644" permission, not exactly "664" but not "640" either. It is weird...

**Comment by ocaisa** [comment]
There is a `--umask='002'` option for EasyBuild, if you want to force the umask behaviour.

**Comment by ponomarevsy** [comment]
Will try that flag, thank you, @ocaisa!

**Comment by ponomarevsy** [comment]
The --umask='002' option for EasyBuild works great (all new module files have -rw-rw-r-- permissions)! Feel free to close this ticket.

**Comment by ocaisa** [comment]
Glad that worked!
