### ISSUE TITLE
Boost 1.76 with iccifort-2020.4.304 failing

### ISSUE THREAD

**Issue by jshelly** [easybuilders/easybuild#695]
We are getting an error message from b2 after copying the Boost-1.74.0-iccifort-2020.4.304.eb to Boost-1.76.0-iccifort-2020.4.304.eb, removed the patch and updated Boost version and checksum. 
RedHat 8.3 (kernel 4.18.0-240.15.1.el8_3, glibc 2.28-127, x86_64)

See log file attached:

[easybuild-Boost-1.76.0-20210423.130833.qCJbL.log.gz](https://github.com/easybuilders/easybuild/files/6378365/easybuild-Boost-1.76.0-20210423.130833.qCJbL.log.gz)

**Comment by Flamefire** [comment]
Can you please also attach the project-config.jam and user-config.jam files (if present) from the failed build folder?

Also adding `--debug-configuration -d+2` to `installopts` in the EC might provide some more insight.

**Comment by Flamefire** [comment]
It seems we need to explicitely put in the path to the intel compilers or B2 might find a system compiler first: https://github.com/boostorg/build/blob/dca10cf20759b0d194f8305356bf155cc5632c0e/src/tools/intel-linux.jam#L100

I.e. it searches (some of) those paths first: https://github.com/boostorg/build/blob/dca10cf20759b0d194f8305356bf155cc5632c0e/src/tools/intel-linux.jam#L55-L74

**Comment by jshelly** [comment]
Here's the project-config.jam file.  I added the *txt suffix, because it would not allow the *jam suffix.  That is the only *.jam file I found in the build directory. 

[project-config.jam.txt](https://github.com/easybuilders/easybuild/files/6379047/project-config.jam.txt)

**Comment by Flamefire** [comment]
This is a real bug in the new version which I reported as https://github.com/bfgroup/b2/issues/23

Working on an EasyBlock change

**Comment by branfosj** [comment]
This is unrelated to the issue stopping the build, but from the project-config.jam
```
path-constant ICU_PATH : /usr ;
```
This suggests that we should add ICU as a dependency.

**Comment by Flamefire** [comment]
Certainly correct.

**Comment by boegel** [comment]
@branfosj Can you open an issue on the ICU aspect for follow-up?

**Comment by branfosj** [comment]
> @branfosj Can you open an issue on the ICU aspect for follow-up?

I've run some tests on Boost now and I've not been able to reproduce the issue.

**Comment by Flamefire** [comment]
This likely means that you don't have ICU installed on that node. B2 has some auto-detection there.
Is that the case?

**Comment by branfosj** [comment]
I've filed https://github.com/easybuilders/easybuild-easyconfigs/issues/12959 for us to check and decide on how to proceed.
