### ISSUE TITLE
Error at building TensorFlow-2.5.0-fosscuda-2020b.eb

### ISSUE THREAD

**Issue by JoaquinDF** [easybuilders/easybuild#730]
Hello,
` EasyBuild 4.4.1`

I am installing TensorFlow, the **dry run** results are the following:

 * [x] $CFGS/m/M4/M4-1.4.18.eb (module: devel/M4/1.4.18)
 * [x] $CFGS/j/Java/Java-11.0.2.eb (module: lang/Java/11.0.2)
 * [x] $CFGS/j/Java/Java-11.eb (module: lang/Java/11)
 * [x] $CFGS/b/Bison/Bison-3.7.1.eb (module: lang/Bison/3.7.1)
 * [x] $CFGS/c/CUDAcore/CUDAcore-11.1.1.eb (module: system/CUDAcore/11.1.1)
 * [ ] $CFGS/b/Bison/Bison-3.5.3.eb (module: lang/Bison/3.5.3)
 * [x] $CFGS/c/cuDNN/cuDNN-8.0.4.30-CUDA-11.1.1.eb (module: numlib/cuDNN/8.0.4.30-CUDA-11.1.1)
 * [x] $CFGS/z/zlib/zlib-1.2.11.eb (module: lib/zlib/1.2.11)
 * [x] $CFGS/h/help2man/help2man-1.47.4.eb (module: tools/help2man/1.47.4)
 * [x] $CFGS/f/flex/flex-2.6.4.eb (module: lang/flex/2.6.4)
 * [x] $CFGS/b/binutils/binutils-2.35.eb (module: tools/binutils/2.35)
 * [x] $CFGS/g/GCCcore/GCCcore-10.2.0.eb (module: compiler/GCCcore/10.2.0)
 * [x] $CFGS/z/zlib/zlib-1.2.11-GCCcore-10.2.0.eb (module: lib/zlib/1.2.11-GCCcore-10.2.0)
 * [x] $CFGS/h/help2man/help2man-1.47.16-GCCcore-10.2.0.eb (module: tools/help2man/1.47.16-GCCcore-10.2.0)
 * [x] $CFGS/m/M4/M4-1.4.18-GCCcore-10.2.0.eb (module: devel/M4/1.4.18-GCCcore-10.2.0)
 * [x] $CFGS/b/Bison/Bison-3.7.1-GCCcore-10.2.0.eb (module: lang/Bison/3.7.1-GCCcore-10.2.0)
 * [x] $CFGS/f/flex/flex-2.6.4-GCCcore-10.2.0.eb (module: lang/flex/2.6.4-GCCcore-10.2.0)
 * [x] $CFGS/b/binutils/binutils-2.35-GCCcore-10.2.0.eb (module: tools/binutils/2.35-GCCcore-10.2.0)
 * [x] $CFGS/n/ncurses/ncurses-6.2-GCCcore-10.2.0.eb (module: devel/ncurses/6.2-GCCcore-10.2.0)
 * [x] $CFGS/c/cURL/cURL-7.72.0-GCCcore-10.2.0.eb (module: tools/cURL/7.72.0-GCCcore-10.2.0)
 * [x] $CFGS/b/bzip2/bzip2-1.0.8-GCCcore-10.2.0.eb (module: tools/bzip2/1.0.8-GCCcore-10.2.0)
 * [x] $CFGS/e/expat/expat-2.2.9-GCCcore-10.2.0.eb (module: tools/expat/2.2.9-GCCcore-10.2.0)
 * [x] $CFGS/l/libreadline/libreadline-8.0-GCCcore-10.2.0.eb (module: lib/libreadline/8.0-GCCcore-10.2.0)
 * [x] $CFGS/p/pkg-config/pkg-config-0.29.2-GCCcore-10.2.0.eb (module: devel/pkg-config/0.29.2-GCCcore-10.2.0)
 * [x] $CFGS/l/libtool/libtool-2.4.6-GCCcore-10.2.0.eb (module: lib/libtool/2.4.6-GCCcore-10.2.0)
 * [x] $CFGS/d/DB/DB-18.1.40-GCCcore-10.2.0.eb (module: tools/DB/18.1.40-GCCcore-10.2.0)
 * [x] $CFGS/g/GCC/GCC-10.2.0.eb (module: compiler/GCC/10.2.0)
 * [x] $CFGS/t/Tcl/Tcl-8.6.10-GCCcore-10.2.0.eb (module: lang/Tcl/8.6.10-GCCcore-10.2.0)
 * [x] $CFGS/z/Zip/Zip-3.0-GCCcore-10.2.0.eb (module: tools/Zip/3.0-GCCcore-10.2.0)
 * [x] $CFGS/u/UnZip/UnZip-6.0-GCCcore-10.2.0.eb (module: tools/UnZip/6.0-GCCcore-10.2.0)
 * [x] $CFGS/n/NCCL/NCCL-2.8.3-GCCcore-10.2.0-CUDA-11.1.1.eb (module: lib/NCCL/2.8.3-GCCcore-10.2.0-CUDA-11.1.1)
 * [x] $CFGS/s/SQLite/SQLite-3.33.0-GCCcore-10.2.0.eb (module: devel/SQLite/3.33.0-GCCcore-10.2.0)
 * [x] $CFGS/l/libffi/libffi-3.3-GCCcore-10.2.0.eb (module: lib/libffi/3.3-GCCcore-10.2.0)
 * [x] $CFGS/n/ncurses/ncurses-6.2.eb (module: devel/ncurses/6.2)
 * [x] $CFGS/p/Perl/Perl-5.32.0-GCCcore-10.2.0-minimal.eb (module: lang/Perl/5.32.0-GCCcore-10.2.0-minimal)
 * [x] $CFGS/g/gettext/gettext-0.21.eb (module: tools/gettext/0.21)
 * [x] $CFGS/m/makeinfo/makeinfo-6.7-GCCcore-10.2.0-minimal.eb (module: devel/makeinfo/6.7-GCCcore-10.2.0-minimal)
 * [x] $CFGS/x/XZ/XZ-5.2.5-GCCcore-10.2.0.eb (module: tools/XZ/5.2.5-GCCcore-10.2.0)
 * [x] $CFGS/g/groff/groff-1.22.4-GCCcore-10.2.0.eb (module: tools/groff/1.22.4-GCCcore-10.2.0)
 * [x] $CFGS/l/libxml2/libxml2-2.9.10-GCCcore-10.2.0.eb (module: lib/libxml2/2.9.10-GCCcore-10.2.0)
 * [x] $CFGS/l/libarchive/libarchive-3.4.3-GCCcore-10.2.0.eb (module: tools/libarchive/3.4.3-GCCcore-10.2.0)
 * [x] $CFGS/p/Perl/Perl-5.32.0-GCCcore-10.2.0.eb (module: lang/Perl/5.32.0-GCCcore-10.2.0)
 * [x] $CFGS/g/gettext/gettext-0.21-GCCcore-10.2.0.eb (module: tools/gettext/0.21-GCCcore-10.2.0)
 * [x] $CFGS/c/CMake/CMake-3.18.4-GCCcore-10.2.0.eb (module: devel/CMake/3.18.4-GCCcore-10.2.0)
 * [x] $CFGS/e/Eigen/Eigen-3.3.8-GCCcore-10.2.0.eb (module: math/Eigen/3.3.8-GCCcore-10.2.0)
 * [x] $CFGS/a/Autoconf/Autoconf-2.69-GCCcore-10.2.0.eb (module: devel/Autoconf/2.69-GCCcore-10.2.0)
 * [x] $CFGS/a/Automake/Automake-1.16.2-GCCcore-10.2.0.eb (module: devel/Automake/1.16.2-GCCcore-10.2.0)
 * [x] $CFGS/d/double-conversion/double-conversion-3.1.5-GCCcore-10.2.0.eb (module: lib/double-conversion/3.1.5-GCCcore-10.2.0)
 * [x] $CFGS/p/protobuf/protobuf-3.14.0-GCCcore-10.2.0.eb (module: devel/protobuf/3.14.0-GCCcore-10.2.0)
 * [x] $CFGS/a/Autotools/Autotools-20200321-GCCcore-10.2.0.eb (module: devel/Autotools/20200321-GCCcore-10.2.0)
 * [x] $CFGS/g/GMP/GMP-6.2.0-GCCcore-10.2.0.eb (module: math/GMP/6.2.0-GCCcore-10.2.0)
 * [x] $CFGS/g/git/git-2.28.0-GCCcore-10.2.0-nodocs.eb (module: tools/git/2.28.0-GCCcore-10.2.0-nodocs)
 * [x] $CFGS/p/Python/Python-3.8.6-GCCcore-10.2.0.eb (module: lang/Python/3.8.6-GCCcore-10.2.0)
 * [x] $CFGS/p/pybind11/pybind11-2.6.0-GCCcore-10.2.0.eb (module: lib/pybind11/2.6.0-GCCcore-10.2.0)
 * [x] $CFGS/p/pkgconfig/pkgconfig-1.5.1-GCCcore-10.2.0-python.eb (module: devel/pkgconfig/1.5.1-GCCcore-10.2.0-python)
 * [x] $CFGS/b/Bazel/Bazel-3.7.2-GCCcore-10.2.0.eb (module: devel/Bazel/3.7.2-GCCcore-10.2.0)
 * [x] $CFGS/h/hypothesis/hypothesis-5.41.2-GCCcore-10.2.0.eb (module: tools/hypothesis/5.41.2-GCCcore-10.2.0)
 * [x] $CFGS/g/giflib/giflib-5.2.1-GCCcore-10.2.0.eb (module: lib/giflib/5.2.1-GCCcore-10.2.0)
 * [x] $CFGS/n/Ninja/Ninja-1.10.1-GCCcore-10.2.0.eb (module: tools/Ninja/1.10.1-GCCcore-10.2.0)
 * [x] $CFGS/s/Szip/Szip-2.1.1-GCCcore-10.2.0.eb (module: tools/Szip/2.1.1-GCCcore-10.2.0)
 * [x] $CFGS/f/flatbuffers/flatbuffers-1.12.0-GCCcore-10.2.0.eb (module: devel/flatbuffers/1.12.0-GCCcore-10.2.0)
 * [x] $CFGS/c/CUDA/CUDA-11.1.1-GCC-10.2.0.eb (module: system/CUDA/11.1.1-GCC-10.2.0)
 * [x] $CFGS/i/ICU/ICU-67.1-GCCcore-10.2.0.eb (module: lib/ICU/67.1-GCCcore-10.2.0)
 * [x] $CFGS/n/numactl/numactl-2.0.13-GCCcore-10.2.0.eb (module: tools/numactl/2.0.13-GCCcore-10.2.0)
 * [x] $CFGS/j/JsonCpp/JsonCpp-1.9.4-GCCcore-10.2.0.eb (module: lib/JsonCpp/1.9.4-GCCcore-10.2.0)
 * [x] $CFGS/o/OpenBLAS/OpenBLAS-0.3.12-GCC-10.2.0.eb (module: numlib/OpenBLAS/0.3.12-GCC-10.2.0)
 * [x] $CFGS/l/libevent/libevent-2.1.12-GCCcore-10.2.0.eb (module: lib/libevent/2.1.12-GCCcore-10.2.0)
 * [x] $CFGS/x/xorg-macros/xorg-macros-1.19.2-GCCcore-10.2.0.eb (module: devel/xorg-macros/1.19.2-GCCcore-10.2.0)
 * [x] $CFGS/l/libpciaccess/libpciaccess-0.16-GCCcore-10.2.0.eb (module: system/libpciaccess/0.16-GCCcore-10.2.0)
 * [x] $CFGS/h/hwloc/hwloc-2.2.0-GCCcore-10.2.0.eb (module: system/hwloc/2.2.0-GCCcore-10.2.0)
 * [x] $CFGS/l/LMDB/LMDB-0.9.24-GCCcore-10.2.0.eb (module: lib/LMDB/0.9.24-GCCcore-10.2.0)
 * [x] $CFGS/l/libfabric/libfabric-1.11.0-GCCcore-10.2.0.eb (module: lib/libfabric/1.11.0-GCCcore-10.2.0)
 * [x] $CFGS/n/NASM/NASM-2.15.05-GCCcore-10.2.0.eb (module: lang/NASM/2.15.05-GCCcore-10.2.0)
 * [x] $CFGS/l/libjpeg-turbo/libjpeg-turbo-2.0.5-GCCcore-10.2.0.eb (module: lib/libjpeg-turbo/2.0.5-GCCcore-10.2.0)
 * [x] $CFGS/n/nsync/nsync-1.24.0-GCCcore-10.2.0.eb (module: devel/nsync/1.24.0-GCCcore-10.2.0)
 * [x] $CFGS/p/PMIx/PMIx-3.1.5-GCCcore-10.2.0.eb (module: lib/PMIx/3.1.5-GCCcore-10.2.0)
 * [x] $CFGS/c/Check/Check-0.15.2-GCCcore-10.2.0.eb (module: lib/Check/0.15.2-GCCcore-10.2.0)
 * [x] $CFGS/g/GDRCopy/GDRCopy-2.1-GCCcore-10.2.0-CUDA-11.1.1.eb (module: lib/GDRCopy/2.1-GCCcore-10.2.0-CUDA-11.1.1)
 * [x] $CFGS/u/UCX/UCX-1.9.0-GCCcore-10.2.0-CUDA-11.1.1.eb (module: lib/UCX/1.9.0-GCCcore-10.2.0-CUDA-11.1.1)
 * [x] $CFGS/p/PCRE/PCRE-8.44-GCCcore-10.2.0.eb (module: devel/PCRE/8.44-GCCcore-10.2.0)
 * [x] $CFGS/g/gcccuda/gcccuda-2020b.eb (module: toolchain/gcccuda/2020b)
 * [x] $CFGS/o/OpenMPI/OpenMPI-4.0.5-gcccuda-2020b.eb (module: mpi/OpenMPI/4.0.5-gcccuda-2020b)
 * [x] $CFGS/g/gompic/gompic-2020b.eb (module: toolchain/gompic/2020b)
 * [x] $CFGS/f/FFTW/FFTW-3.3.8-gompic-2020b.eb (module: numlib/FFTW/3.3.8-gompic-2020b)
 * [x] $CFGS/s/ScaLAPACK/ScaLAPACK-2.1.0-gompic-2020b.eb (module: numlib/ScaLAPACK/2.1.0-gompic-2020b)
 * [x] $CFGS/h/HDF5/HDF5-1.10.7-gompic-2020b.eb (module: data/HDF5/1.10.7-gompic-2020b)
 * [x] $CFGS/f/fosscuda/fosscuda-2020b.eb (module: toolchain/fosscuda/2020b)
 * [x] $CFGS/s/SciPy-bundle/SciPy-bundle-2020.11-fosscuda-2020b.eb (module: lang/SciPy-bundle/2020.11-fosscuda-2020b)
 * [x] $CFGS/h/h5py/h5py-3.1.0-fosscuda-2020b.eb (module: data/h5py/3.1.0-fosscuda-2020b)
 * [x] $CFGS/p/protobuf-python/protobuf-python-3.14.0-GCCcore-10.2.0.eb (module: devel/protobuf-python/3.14.0-GCCcore-10.2.0)
 * [x] $CFGS/f/flatbuffers-python/flatbuffers-python-1.12-GCCcore-10.2.0.eb (module: devel/flatbuffers-python/1.12-GCCcore-10.2.0)
 * [x] $CFGS/t/typing-extensions/typing-extensions-3.7.4.3-GCCcore-10.2.0.eb (module: devel/typing-extensions/3.7.4.3-GCCcore-10.2.0)
 * [x] $CFGS/l/libpng/libpng-1.6.37-GCCcore-10.2.0.eb (module: lib/libpng/1.6.37-GCCcore-10.2.0)
 * [x] $CFGS/s/snappy/snappy-1.1.8-GCCcore-10.2.0.eb (module: lib/snappy/1.1.8-GCCcore-10.2.0)
 * [ ] $CFGS/t/TensorFlow/TensorFlow-2.5.0-fosscuda-2020b.eb (module: lib/TensorFlow/2.5.0-fosscuda-2020b)

I install following the same command 
`eb TensorFlow-2.5.0-fosscuda-2020b.eb -r --cuda-compute-capabilities 7.0`

And I got the following error:
`== installing extension TensorFlow 2.5.0 (30/30)...
==     configuring...
==     building...
==     testing...
== ... (took 2 hours 12 mins 35 secs)
== FAILED: Installation ended unsuccessfully (build directory: /home/users/xxxxx/.local/easybuild/build/TensorFlow/2.5.0/fosscuda-2020b): build failed (first 300 chars): At least 1 cpu tests failed:
//tensorflow/python/data/experimental/kernel_tests:non_serializable_test (took 2 hours 17 mins 19 secs)
== Results of the build can be found in the log file(s) /tmp/eb-NnFMfj/easybuild-TensorFlow-2.5.0-20210730.182118.ubxhX.log`

Any clues how to solve it?

Thanks

**Comment by boegel** [comment]
@JoaquinDF Did you figure out what was wrong? Can you share some more info on how you solved the issue?

**Comment by JoaquinDF** [comment]
Helo @boegel .

It was completely on my side. 
The error was because I have a file's quota and following _inode_ the build was around 1M files.
so, no issues on your side :)

Thanks
