### ISSUE TITLE
Update of generic buildblocks overview document

### ISSUE THREAD

**Issue by maiconfaria** [easybuilders/easybuild#733]
There is removed options that are still in the documentation: https://docs.easybuild.io/en/develop/version-specific/generic_easyblocks.html

For example use_easy_install.

**Comment by boegel** [comment]
Thanks for reporting this @maiconfaria!

That part of the documentation is auto-generated based on what the easyblocks still recognize as custom easyconfig parameters.

You're correct in the case of `use_easy_install`, that will be fixed once https://github.com/easybuilders/easybuild-easyblocks/pull/2535 is merged, and the documentation is subsequently updated for the next EasyBuild release.
