### ISSUE TITLE
Upgrading easybuild from 4.3.2 installed with bootstrap_eb

### ISSUE THREAD

**Issue by jd-daniels** [easybuilders/easybuild#735]
I installed easybuild a while ago like so:

curl -O https://raw.githubusercontent.com/easybuilders/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py
module load python39
python bootstrap_eb.py /cm/shared/easybuild

It looks like the install/upgrade documentation has change quite a bit.
What upgrade procedure should I follow? I tried via pip and via module install, but I had various problems with both.
Before I proceed debugging I want to make sure I'm following the proper procedure.

I think it should be via module install because that appears to be what I have already?

Thanks.

**Comment by boegel** [comment]
The recommend procedures are documented at https://docs.easybuild.io/en/latest/Installation.html .
