### ISSUE TITLE
Please add possibility to skip certificate check while fetching files

### ISSUE THREAD

**Issue by Pupkur** [easybuilders/easybuild#743]
== 2021-10-22 02:18:01,974 filetools.py:628 WARNING IOError occurred while trying to download https://xorg.freedesktop.org/archive/individual/data//xkeyboard-config/libxkbcommon-0.8.0.tar.xz to /apps/sources/x/X11/libxkbcommon-0.8.0.tar.xz: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>

**Comment by boegel** [comment]
Support for `--insecure-download` was implemented in EasyBuild v4.5.0 (see https://github.com/easybuilders/easybuild-framework/pull/3859), so closing this issue...
