### ISSUE TITLE
ERROR: No compatible 'python' command found via $PATH (EasyBuild requires Python 2.6+ or 3.5+)

### ISSUE THREAD

**Issue by chaseschuette** [easybuilders/easybuild#787]
Easybuild was pip installed system-wide on Ubuntu 18.04 with these currently env vars set.

PYTHONPATH="/apps/easybuild/lib/python2.7.17/site-packages"
EB_PYTHON="/usr/bin/python3.6"

I also tried with EB_PYTHON="/usr/bin/python"

Here's some verbose output:

eb --install-latest-eb-release
>> Considering 'python'...
>> 'python' version: 2.7.17, which matches Python 2 version requirement (>= 2.6)
>> 'python' is NOT able to import 'easybuild.main', so NOT retaining it
>> Considering 'python3'...
>> 'python3' version: 3.6.5, which matches Python 3 version requirement (>= 3.5)
>> 'python3' is NOT able to import 'easybuild.main', so NOT retaining it
>> Considering 'python2'...
>> 'python2' version: 2.7.17, which matches Python 2 version requirement (>= 2.6)
>> 'python2' is NOT able to import 'easybuild.main', so NOT retaining it
ERROR: No compatible 'python' command found via $PATH (EasyBuild requires Python 2.6+ or 3.5+)

I saw this relevant thread https://githubhot.com/repo/easybuilders/easybuild-framework/issues/3846

**Comment by boegel** [comment]
> PYTHONPATH="/apps/easybuild/lib/python2.7.17/site-packages"
> EB_PYTHON="/usr/bin/python3.6"

This is definitely wrong: it should be `python2.7/site-packages` (just major.minor Python version), and if EasyBuild was installed with Python 2.x, you shouldn't tell it to run with Python 3.6, that may lead to tears.

To check what's going on, you should run without the `eb` wrapper script:

```
python -m easybuild.main
```

We've also discussed this in the EasyBuild Slack, and I think the problems you were seeing have been resolved, can you confirm?

**Comment by chaseschuette** [comment]
That was a typo in the python version.

However, it appears to be fixed with appending /apps/easybuild/lib/python2.7/site-packages to $PATH

eb --version
>> Considering '/usr/bin/python3.6'...
>> '/usr/bin/python3.6' version: 3.6.5, which matches Python 3 version requirement (>= 3.5)
>> '/usr/bin/python3.6' is NOT able to import 'easybuild.main', so NOT retaining it
>> Considering 'python'...
>> 'python' version: 2.7.17, which matches Python 2 version requirement (>= 2.6)
>> 'python' is able to import 'easybuild.main', so retaining it
>> Selected Python command: python (/usr/bin/python)
>> python -m easybuild.main --version
This is EasyBuild 4.5.3 (framework: 4.5.3, easyblocks: 4.5.3) on host XXX


There may be some unintended effects that I managed to workaround

**Comment by boegel** [comment]
I don't see how adding `.../site-packages` to `$PATH` can fix the problem, that doesn't make much sense to me...

This should do it for you:

```
export PYTHONPATH=/apps/easybuild/lib/python2.7/site-packages
export PATH=/apps/easybuild/bin:$PATH
```

**Comment by ernstki** [comment]
Also, while tempting, don't use [pipx](https://pipx.pypa.io/stable/) to try to install easybuild. The first sign of trouble with `pipx install` is:

```
$ pipx install easybuild
Note: Dependent package 'easybuild-framework' contains 6 apps
  - eb
  - eb_bash_completion.bash
  - eb_bash_completion_local.bash
  - install_eb_dep.sh
  - minimal_bash_completion.bash
  - optcomplete.bash

No apps associated with package easybuild. Try again with '--include-deps' to include apps of dependent packages, which are listed above. If you are
attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
```

If you persist and add `--include-deps`, it _appears_ everything works correctly, and the helper scripts like `eb` _will_ be in your path, but you'll still get this unhelpful error:

```console
$ eb --show-default-configfiles
ERROR: No compatible 'python' command found via $PATH (EasyBuild requires Python 3.6+)
```

…regardless of whether your `python --version` meets the requirements. The problem is **not** that you don't have a compatible `python`, it's that the `python` you _do_ have can't find the `site-packages` associated with the pipx installation.

It's true that you can work around that like this:

```console
$ export PYTHONPATH=$HOME/.local/pipx/venvs/easybuild/lib/python3.10/site-packages
$ eb --show-default-configfiles
```

…but at that point, you might as well create a [virtualenv](https://docs.python.org/3/library/venv.html) somewhere else and just do the recommended `pip install`, or `pip install --user` or `pip install` as root and suffer the consequences later.
