### ISSUE TITLE
easybuild doesn't find installed OS dependencies 

### ISSUE THREAD

**Issue by LukeLabrie** [easybuilders/easybuild#833]
running into the following error on Arch 

```
One or more OS dependencies were not found: [('python-pandas', 'python-h5py', 'python-matplotlib', 'python-uncertainties', 'python-scipy', 'python-numpy', 'python-lxml')]
```

but these packages are installed; output of `pacman -Q python-pandas python-h5py python-matplotlib python-uncertainties python-scipy python-numpy python-lxml`:

```
python-pandas 1.4.4-1
python-h5py 3.7.0-1
python-matplotlib 3.5.2-1
python-uncertainties 3.1.7-1
python-scipy 1.9.3-1
python-numpy 1.23.4-1
python-lxml 4.9.1-1
```
how does easybuild check for os dependencies? 

i tried adding the install locations to my path, which didn't help. not sure if this is related to #818 maybe? just seems like easybuild can't locate any os dependencies for me currently. i know that for the dependencies above i could add them as dependencies instead of os dependencies, but i'd rather not

let me know if i can provide more detail

**Comment by LukeLabrie** [comment]
I'm thinking it doesn't make sense to list these as os dependencies. I took a look at the python logic for os dependencies and it will look for executables, which won't work on python modules

**Comment by boegel** [comment]
@LukeLabrie EasyBuild currently doesn't know how to check for OS dependencies in Arch, it's only checking with commands like `rpm`, etc.

The code in `check_os_dependency` (see https://github.com/easybuilders/easybuild-framework/blob/adb9086598c2c0b776659710da0fa3040fc4de12/easybuild/tools/systemtools.py#L816) should be enhanced to be made aware of `Arch`/`pacman`
