### ISSUE TITLE
No module named pip found - Installing EB with EB procedure

### ISSUE THREAD

**Issue by nicolalogullo** [easybuilders/easybuild#858]
Hello,
I have problems in trying to install EB using a temporary EB installation.

The error I get is:

``` 
ERROR: Build of /tmp/eb-ytwh1saz/tmp8vz_8_zs/easybuilders/easybuild-easyconfigs-develop/easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.7.0.eb failed (err: 'build failed (first 300 chars): cmd "/usr/bin/python3.6 -m pip --version" exited with exit code 1 and output:\n/usr/bin/python3.6: No module named pip\n')
```

However if I look at the log file, few steps above I can see that it managed to determine the right version of pip:

```
== 2023-01-30 16:42:05,666 easybuildmeta.py:74 INFO Python version: 3.6.8
== 2023-01-30 16:42:05,667 pythonpackage.py:212 INFO Determining pip version...
== 2023-01-30 16:42:05,667 run.py:236 INFO running cmd: /usr/bin/python3.6 -m pip --version
== 2023-01-30 16:42:06,312 pythonpackage.py:220 INFO Found pip version: 21.3.1
== 2023-01-30 16:42:06,313 easybuildmeta.py:81 INFO Found Python v3.6.8 + pip: 21.3.1
== 2023-01-30 16:42:06,313 easybuildmeta.py:86 INFO Auto-enabling use of pip to install EasyBuild!
== 2023-01-30 16:42:06,313 pythonpackage.py:338 INFO Using pip with --no-deps option
== 2023-01-30 16:42:06,314 environment.py:93 INFO Environment variable XDG_CACHE_HOME set to /tmp/eb-ytwh1saz (previously undefined)
```
Does anyone know what the problem could be?

I am following the "Method 2" instructions to install EB with a temporary installation of EB.

Thanks!

**Comment by boegel** [comment]
@nicolalogullo Can you share some more information about the system you're running this on? Which OS, etc.?

Can you share the output of `eb --show-system-info` with the temporary installation of EasyBuild you have?

Also, can you collect a debug log when installing EasyBuild with EasyBuild (using `eb --debug`), and share the bit at the end (which includes the error but also a couple of lines above, which shows how the `pip --version` command is being run?

**Comment by nicolalogullo** [comment]
Hello @boegel !

Ok so this is the info you requested:

```
System information (newton-fe):

* OS:
  -> name: CentOS
  -> type: Linux
  -> version: 6.6
  -> platform name: x86_64-unknown-linux

* CPU:
  -> vendor: Intel
  -> architecture: x86_64
  -> family: Intel
  -> arch name: UNKNOWN (archspec is not installed?)
  -> model: Intel(R) Xeon(R) CPU E5-2609 v2 @ 2.50GHz
  -> speed: 2500.082
  -> cores: 8
  -> features: acpi,aes,aperfmperf,apic,arat,arch_perfmon,avx,bts,clflush,cmov,constant_tsc,cx16,cx8,dca,de,ds_cpl,dtes64,dts,dts,epb,ept,erms,est,f16c,flexpriority,fpu,fsgsbase,fxsr,ht,lahf_lm,lm,mca,mce,mmx,monitor,msr,mtrr,nonstop_tsc,nx,pae,pat,pbe,pcid,pclmulqdq,pdcm,pdpe1gb,pebs,pge,pln,pni,popcnt,pse,pse36,pts,rdrand,rdtscp,rep_good,sep,smep,smx,ss,sse,sse2,sse4_1,sse4_2,ssse3,syscall,tm,tm2,tpr_shadow,tsc,tsc_deadline_timer,vme,vmx,vnmi,vpid,x2apic,xsave,xsaveopt,xtopology,xtpr

* software:
  -> glibc version: 2.12
  -> Python binary: /usr/bin/python3.6
  -> Python version: 3.6.8

```
(Unfortunately it is somehow an outdated system, but for now that is the one I have available for these tests.)

Attached is the full log for one of the installations I attempted.
I am not sure if the reset of the environment is causing this.

[easybuild-EasyBuild-4.7.0-20230130.164205.ynRds.log](https://github.com/easybuilders/easybuild/files/10555082/easybuild-EasyBuild-4.7.0-20230130.164205.ynRds.log)

**Comment by boegel** [comment]
@nicolalogullo Oh boy, CentOS 6 is indeed pretty ancient...

It's indeed possible that environment changes being made result in `pip` no longer being found, and it may have something to do with how Python 3 + `pip` were installed (since there are no standard packages for those on CentOS 6, I think).

Can you run the following commands, and share the output?

```
eb --show-config
echo "PYTHONPATH=$PYTHONPATH"
/usr/bin/python3.6 -c 'import pip; print(pip.__file__)'
/usr/bin/python3.6 -c 'import sys; print(sys.path)'
```

**Comment by nicolalogullo** [comment]
@boegel  ok, here is what you asked for:
```
> export EB_PYTHON=python3.6
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath      (D) = /home/logullon/.local/easybuild/build
containerpath  (D) = /home/logullon/.local/easybuild/containers
installpath    (D) = /home/logullon/.local/easybuild
repositorypath (D) = /home/logullon/.local/easybuild/ebfiles_repo
robot-paths    (D) = /home/logullon/eb_tmp/easybuild/easyconfigs
sourcepath     (D) = /home/logullon/.local/easybuild/sources

```

```
> echo "PYTHONPATH=$PYTHONPATH"
PYTHONPATH=/home/logullon/eb_tmp//lib/python3.6/site-packages

```
```
> /usr/bin/python3.6 -c 'import pip; print(pip.__file__)'
/usr/local/lib/python3.6/site-packages/pip/__init__.py
```
```
> /usr/bin/python3.6 -c 'import sys; print(sys.path)'
['', '/home/logullon/eb_tmp/lib/python3.6/site-packages', '/usr/lib64/python36.zip', '/usr/lib64/python3.6', '/usr/lib64/python3.6/lib-dynload', '/usr/local/lib64/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']
```
All this by setting up the EB environment variables as in the EB installation guide Method 2

**Comment by boegel** [comment]
Can you check if you're still seeing the problem after first running this (before you install EB with EB):

```shell
export PYTHONPATH=/usr/local/lib/python3.6/site-packages
```

It looks like `$PYTHONPATH` is not set at all by default, but when it's set (done by EasyBuild when it installs the `easybuild-framework` Python package) then the `/usr/local/lib/python3.6/site-packages` is no longer being considered by `python3.6`, and hence it "loses" `pip`...

**Comment by nicolalogullo** [comment]
I think I tried that before and I got (and I still get) this error:

```
> eb --install-latest-eb-release --prefix /home/logullon/eb_test/easybuild
ERROR: No compatible 'python' command found via $PATH (EasyBuild requires Python 2.6+ or 3.5+)

```

Same thing if I try to use this (but not sure how relevant it is in this situation):

```
> eb --install-latest-eb-release *--try-amend=use_pip=1* --prefix /home/logullon/eb_test/easybuild
ERROR: No compatible 'python' command found via $PATH (EasyBuild requires Python 2.6+ or 3.5+)
```

**Comment by nicolalogullo** [comment]
Solved by using a virtual env.

After that, removing the venv and loading the EB module works perfectly.

Thanks for the help!
