### ISSUE TITLE
Checksum verification fails when building UCX-1.13.1-GCCcore-12.2.0.eb  (using EB 4.7.0)

### ISSUE THREAD

**Issue by bphusted** [easybuilders/easybuild#860]
I tried building UCX-1.13.1-GCCcore-12.2.0.eb, but got a checksum error using EasyBuild 4.7.0.
Then I tried to download the file manually from github and got the same checksum as reported by easybuild.
So somehow there is a mismatch between the checksum in the installation file and file downloaded from github.

Checksum verification for /sw/easybuild/sources/u/UCX/ucx-1.13.1.tar.gz using {'ucx-1.13.1.tar.gz': 'efc37829b68e131d2acc82a3fd4334bfd611156a756837ffeb650ab9a9dd3828'} failed.")

**Comment by boegel** [comment]
@bphusted That problem is caused by an in-place update of the UCX 1.13.1 source tarball, see https://github.com/easybuilders/easybuild-easyconfigs/pull/17077 for more information.

You can work around the problem with EasyBuild v4.7.0 using `eb --from-pr 17077 UCX-1.13.1-GCCcore-12.2.0.eb`)
