### ISSUE TITLE
Minimum supported Lmod Version - EasyBuild 5

### ISSUE THREAD

**Issue by branfosj** [easybuilders/easybuild#871]
Work has started on [EasyBuild 5](https://docs.easybuild.io/easybuild-v5/overview-of-changes) and we, the EasyBuild maintainers, are requesting community feedback on some potential changes. If you will be impacted by this proposed change then please leave feedback below.

## Proposed Change

Change the minimum supported Lmod version to be 7.

*This proposed change only relates to supported Lmod version. No change is proposed for support of other module tools.*

## Background

Lmod 6 is old - the most recent release being several years ago. Use of [Lmod 6 is deprecated](https://docs.easybuild.io/deprecated-functionality/#depr_lmod6) in EasyBuild and the intention is to remove support in EasyBuild 5.

## Benefits

* Motivate community to adopt Lmod 8.x
* Makes the change notified by the current deprecation warning
* Simplify CI test configurations

## Drawbacks

* Ubuntu / Debian Lmod 6.x
  * Lmod packages available via https://github.com/surak/Lmod
  * Not every EasyBuild user is able to install updated packages
* This will not produce significant code simplification

**Comment by boegel** [comment]
My 2 cents: maybe we should even consider requiring Lmod 8.x - I see no reason for keeping support for Lmod 7 if we won't support Lmod 6 anymore (both are old enough to be basically irrelevant now) - although I may be overlooking something.

In addition, we probably *should* consider also removing support for some ancient Environment Modules versions that nobody is using anymore - in particular the `EnvironmentModulesTcl` class that supports the ancient Tcl-only implementation (which predates even the 3.x Tcl/C implementation, cfr. https://github.com/cea-hpc/modules/blob/main/NEWS.rst#modules-tcl-1923-2017-07-20).
Note that the modern Tcl-only 4.x implementation is supported via the `EnvironmentModules` class.

We may need to keep the support for 3.x Tcl/C implementation (`EnvironmentModulesC` class) though, I suspect that's still used in the wild quite a bit, despite the last release dating from 2012-12-20 (cfr. https://sourceforge.net/projects/modules/files/Modules/modules-3.2.10/).
The [last EasyBuild survey (2022)](https://docs.easybuild.io/user-survey/#other-tools-projects) shows that we were still around 10% usage there (same ballpark as Lmod 6.x, but still the most used Tcl-based implementation).

**Comment by branfosj** [comment]
> My 2 cents: maybe we should even consider requiring Lmod 8.x - I see no reason for keeping support for Lmod 7 if we won't support Lmod 6 anymore (both are old enough to be basically irrelevant now) - although I may be overlooking something.

The problem point is the availability of Lmod 8 on Ubuntu (20.04 and 22.04). Especially for those who do not control the installed packages on the system.

We need make a separate proposal for other module tools. I've explicitly stated: "This proposed change only relates to supported Lmod version. No change is proposed for support of other module tools." and that no longer is true.

**Comment by signalbox2** [comment]
Lmod can be installed without root privilege as documented here: [https://mdc-easybuild.readthedocs.io/en/latest/Installing-Lmod-without-root-permissions.html](url) and that is what we do to maintain EasyBuild and Lmod on a large HPC where we are just normal users.   It is CentOS 7 but I am assuming that it also works for Ubuntu, so I am in favour of seeing if users can be pushed to Lmod 8.  I'm sure Robert McLay would be grateful.   But perhaps an Ubuntu user should comment.

**Comment by boegel** [comment]
@surak What are your thoughts on this, since you maintain Lmod packages for Ubuntu in https://github.com/surak/Lmod/releases ?

**Comment by surak** [comment]
Go for it. First because Debian stable already picked it up, and so will the next ubuntu.

I am discussing with Ubuntu to make a backport for the 20 and 22. They are not fond of changing packages on old distributions like this, but I am still trying to make the case for it.

In any case, there are packages for the system which I provide.

**Comment by surak** [comment]
The current discussion with ubuntu people is that the best option is to create a PPA, as this is not a security update. That would also work with debian if one adds the debian version on the ppa.

**Comment by branfosj** [comment]
Having discussed this with the community, we have decided that the minimum support Lmod version for EasyBuild 5 will be Lmod 8.0.0. See https://github.com/easybuilders/easybuild-framework/pull/4424
