### ISSUE TITLE
HDF5-1.13.1-iimpi-2022a.eb download failure

### ISSUE THREAD

**Issue by wrussian** [easybuilders/easybuild#875]
Hello, I'm using eb-4.7.2, sles15.4, hw AMD7763.
Trying to install  HDF5-1.13.1-iimpi-2022a.eb  results in an error downloading the hdf5 - tar archive:

... 
== 2023-06-23 17:28:00,712 filetools.py:833 WARNING URL https://support.hdfgroup.org/
> ftp/HDF5/releases/hdf5-1.13/hdf5-1.13.1/src/hdf5-1.13.1.tar.gz was not found (HTTP re
> sponse code 404), not trying again

== 2023-06-23 17:28:00,823 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/software/EasyBuild/4.7.2
/lib/python3.6/site-packages/easybuild/base/exceptions.py:126 in __init__): Couldn't find file hdf5-1.13.1.tar.gz anywhere, and 
downloading it didn't work either...
...
Trivial reason is that the URI 
> https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.13/hdf5-1.13.1/src/ 
is empty (also 1.31.0), while 1.31.{2, 3} contain the file archive still. Workaround for me was to create a new file
$CFGS1/h/HDF5/HDF5-1.13.3-iimpi-2022a.eb:

...
version = '1.13.3'

homepage = 'https://portal.hdfgroup.org/display/support'
description = """HDF5 is a data model, library, and file format for storing and managing data.
 It supports an unlimited variety of datatypes, and is designed for flexible
 and efficient I/O and for high volume and complex data."""

toolchain = {'name': 'iimpi', 'version': '2022a'}
toolchainopts = {'pic': True, 'usempi': True}

source_urls = ['https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-%(version_major_minor)s/hdf5-%(version)s/src']
sources = [SOURCELOWER_TAR_GZ]
checksums = ['83c7c06671f975cee6944b0b217f95005faa55f79ea5532cf4ac268989866af4']

dependencies = [
    ('zlib', '1.2.12'),
    ('Szip', '2.1.1'),
]

moduleclass = 'data'
...

**Comment by wrussian** [comment]
unfortunately it doesn't work. Both corrections break with compiler error. I wonder whether it is possible to compile hdf for 1.13.1, if it could be downloaded still. Both build breaks, because as far as I understand SSE functionalty isn't available for AMD 7763.
[easybuild-HDF5-1.13.2-20230623.182719.onpcT.log](https://github.com/easybuilders/easybuild/files/11851660/easybuild-HDF5-1.13.2-20230623.182719.onpcT.log)
[easybuild-HDF5-1.13.3-20230623.181733.BgRlB.log](https://github.com/easybuilders/easybuild/files/11851716/easybuild-HDF5-1.13.3-20230623.181733.BgRlB.log)

**Comment by wrussian** [comment]
I'm sorry, I overlooked #16153. Many thanks for the clarification. I'll try another toolchain.

**Comment by ocaisa** [comment]
Looks like this is resolved
