### ISSUE TITLE
ELPA-2022.05.001-foss-2022b-CUDA-12.0.0.eb compiled success with V100 but failed with A100

### ISSUE THREAD

**Issue by fangrh** [easybuilders/easybuild#882]
I have successful build the eb package ELPA-2022.05.001-foss-2022b-CUDA-12.0.0.eb alone with V100 Nvidia GPU. But when I switch to using the A100 Nvidia GPU. It failed and throw the error blow.

failed (err: 'build failed (first 300 chars): cmd "./autogen.sh && export LDFLAGS="-lm $LDFLAGS" && autoreconf &&  ./configure --prefix=/scratch/work/fangr1/easybuild/software/ELPA/2022.05.001-foss-2022b-CUDA-12.0.0-a100 --disable-openmp  --enable-shared  --enable-generic  --enable-single-precision  --enable-avx  --enable-avx2  --disable-avx512')

**Comment by boegel** [comment]
@fangrh We'll need more information here, can you dig up the actual errors from the EasyBuild log?

**Comment by fangrh** [comment]
Hi, I have found the key problem and this is not easybuild's fault. In our cluster the A100 is together with AMD GPU. But I compiled other dependencies in intel GPU.

**Comment by ocaisa** [comment]
This looks like it is resolved
