### ISSUE TITLE
LAMMPS-23Jun2022-foss-2022a-kokkos : kokkos_arch variable not detected

### ISSUE THREAD

**Issue by theGitpster45** [easybuilders/easybuild#884]
Greetings, 
For a few weeks I tried to deal with a bug that keeps me from successfully installing LAMMPS in my cluster. It always return the following error:

> WARNING: kokkos_arch not set. Trying to auto-detect CPU arch.
(...)
 Couldn't determine CPU architecture, you need to set 'kokkos_arch' manually. (took
17 secs)

I tried to apply the following workarounds, but none worked:

- Copy the original easyconfig for LAMMPS-23Jun2022-foss-2022a-kokkos and set either the `configopts` or `buildopts` options. These are the values I tried:

    - `"-DKokkos_ARCH=HSW"`
    - `"-Dkokkos_arch=HSW"`
    - `"-DKOKKOS_ARCH=HSW"`
    - `"-DKokkos_ARCH_HSW=ON"`
    - `"-Dkokkos_arch_HSW=ON"`
    - `"-DKOKKOS_ARCH_HSW=ON"`
- run the eb command with the --try-amend option (`--try-amend=configopts="-DKokkos_ARCH=HSW"`

**Comment by ocaisa** [comment]
It's not a Lammps option, it's an option for the easyconfig recipe. For what you want, this should work `--try-amend=kokkos_arch=HSW`

**Comment by theGitpster45** [comment]
It worked as you said ! 
Many thanks @ocaisa  :smiley:  !!
