### ISSUE TITLE
Is there any ways to download files dependent to NAMD-2.14-foss-2022a-mpi.eb. all at once

### ISSUE THREAD

**Issue by beeeback** [easybuilders/easybuild#887]
The problem i am facing is i can download all the necessary files for the installation of NAMD manually, but i was searching if there is any method to download all these necessary files at once. I also faced similar problem with GROMACS and had to download all these files manually one by one
binutils-2.40.tar.gz
mpfr-4.2.0.tar.bz2
mpc-1.3.1.tar.gz
automake-1.16.5.tar.gz
make-4.4.1.tar.gz
libtool-2.4.7.tar.gz

I guess it would be easier if Easybuild could provide me all the files that are necessary to install the software (NAMD in my case) all at once like this so i wouldn't have to wait till the installation fails and have to go installing manually till downloading all the necessary file (if some commands already exists please let me know).

Thank you.

**Comment by ocaisa** [comment]
You can use `eb --fetch --robot NAMD-2.14-foss-2022a-mpi.eb` I think

**Comment by ocaisa** [comment]
That will just download the source files. You still may have issues actually installing the software...

**Comment by beeeback** [comment]
Thanks, but that still doesnt solve my problem, it only batch downloads sources on my machine if no modules was installed. My question was if there was any way to see all the files that must be installed for me to be able to download my software.
Thank you.

**Comment by ocaisa** [comment]
Sorry, I don't really understand the question. When you say "all the files that must be installed" it's not really clear to me what you mean. The source files and the files installed are not the same. You originally listed sources, so I assumed you meant you wanted the sources. The command I gave downloads all the sources you would need to install NAMD, EasyBuild is the tool that installs that software.

Perhaps you can be more explicit on what the failure you are seeing is?

**Comment by beeeback** [comment]
The sources i mentioned needed to be installed manually, because the comment that easybuild provided me was, it couldn't find them and Downloading also didnt work. So, i had to download them maually. So, my question is if there is a way i could find all the sources that easybuild needs for a software i can download them all at a once. LIke this way, my installtion wouldn't be stopped every time it doesnt find the source.
Thank you.

**Comment by ocaisa** [comment]
The command I gave you (`eb --fetch --robot NAMD-2.14-foss-2022a-mpi.eb`) will download all the sources for you and let you know about the ones it cannot. That's not perfect though as some applications may download additional things during their build (but it should work in most cases). That assumes that where you are running the command can access the internet of course, if you need a proxy there's some info in https://www.mail-archive.com/easybuild@lists.ugent.be/msg06157.html.

**Comment by beeeback** [comment]
Thank you very much, i also had another doubt regarding changing the .eb files, in my case i need NAMD(memory optimised) version and all the eb files of NAMD present in the github repo were without memory optimised version. Do you have any idea how i can create my own eb file for NAMD with memory optimised version. I am not sure if there are any flags or something like that. Once again thank you for your help.

**Comment by ocaisa** [comment]
Sorry, I have no experience with NAMD, you can joing the EasyBuild Slack channel to ask there for some guidance: https://join.slack.com/t/easybuild/shared_invite/zt-1kvpg7pir-4Je6MZbktn8kYuPTILvdGQ
