### ISSUE TITLE
OpenFOAM-v2312-foss-2023a.eb installation issues

### ISSUE THREAD

**Issue by carlos-encs** [easybuilders/easybuild#897]
Hi 

I tried to install: OpenFOAM-v2312-foss-2023a.eb

The installation process stops at: SciPy-bundle-2023.07-gfbf-2023a.eb at numpy test

ERROR: Build of /nfs/speed-scratch/carlos/easybuild/software/EasyBuild/4.9.2/easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2023.07-gfbf-2023a.eb failed (err: 'build failed (first 300 chars): cmd "export PYTHONPATH=/disk/nobackup2/eb-_k4om6np/tmplynbch4g/lib/python3.11/site-packages:$PYTHONPATH &&  unset LDFLAGS && cd .. && /nfs/speed-scratch/carlos/easybuild/software/Python/3.11.3-GCCcore-12.3.0/bin/python -c \'import sys; import numpy; sys.exit(not numpy.test(verbose=2))\' " exited with ')

eb --version
This is EasyBuild 4.9.2 (framework: 4.9.2, easyblocks: 4.9.2)

Please help

**Comment by ocaisa** [comment]
There's not enough information here to know what is going wrong, have you taken a look at the end of the log file?

**Comment by carlos-encs** [comment]
> There's not enough information here to know what is going wrong, have you taken a look at the end of the log file?

This is the end of the log file:

========================================================================== short test summary info ===========================================================================
FAILED distutils/tests/test_exec_command.py::TestExecCommand::test_basic - AssertionError
============================== 1 failed, 33891 passed, 1592 skipped, 1308 deselected, 31 xfailed, 4 xpassed, 420 warnings in 196.71s (0:03:16) ===============================
 (at easybuild/software/EasyBuild/4.9.2/lib/python3.11/site-packages/easybuild/tools/run.py:682 in parse_cmd_output)
== 2024-07-23 11:55:55,283 build_log.py:267 INFO        ... (took 6 mins 1 secs)
== 2024-07-23 11:55:55,283 build_log.py:267 INFO ... (took 6 mins 8 secs)
== 2024-07-23 11:55:55,283 config.py:700 DEBUG software install path as specified by 'installpath' and 'subdir_software': /nfs/speed-scratch/carlos/easybuild/software
== 2024-07-23 11:55:55,283 filetools.py:2013 INFO Removing lock /nfs/speed-scratch/carlos/easybuild/software/.locks/_nfs_speed-scratch_carlos_easybuild_software_SciPy-bundle_2023.07-gfbf-2023a.lock...
== 2024-07-23 11:55:55,285 filetools.py:383 INFO Path /nfs/speed-scratch/carlos/easybuild/software/.locks/_nfs_speed-scratch_carlos_easybuild_software_SciPy-bundle_2023.07-gfbf-2023a.lock successfully removed.
== 2024-07-23 11:55:55,285 filetools.py:2017 INFO Lock removed: /nfs/speed-scratch/carlos/easybuild/software/.locks/_nfs_speed-scratch_carlos_easybuild_software_SciPy-bundle_2023.07-gfbf-2023a.lock
== 2024-07-23 11:55:55,285 easyblock.py:4285 WARNING build failed (first 300 chars): cmd "export PYTHONPATH=/disk/nobackup2/eb-ztyw8jm1/tmpxb6zuciw/lib/python3.11/site-packages:$PYTHONPATH &&  unset LDFLAGS && cd .. && /nfs/speed-scratch/carlos/easybuild/software/Python/3.11.3-GCCcore-12.3.0/bin/python -c 'import sys; import numpy; sys.exit(not numpy.test(verbose=2))' " exited with
== 2024-07-23 11:55:55,285 easyblock.py:328 INFO Closing log for application name SciPy-bundle version 2023.07

**Comment by carlos-encs** [comment]
I skipped the numpy tests result, modifying this:

find $EBROOTEASYBUILD -name numpy.py

'ignore_test_result': [True, 

It worked, but I feel it's not the right way to do it, SciPy-bundle-2023.07-gfbf-2023a.eb should pass the numpy tests.

Please advise.

**Comment by ocaisa** [comment]
I don't think I would worry about this too much, you have a single failed test out of almost 34k (and from https://github.com/raydeann/numpy/blob/master/numpy/distutils/tests/test_exec_command.py#L203 it looks like that is deprecated functionality). The way you have patched the build, it looks like you directly edited the easyblock so you are still testing `SciPy`, I don't think you have anything to worry about here.

You can of course execute the failing test and see where it is going wrong. Usually something like this would show up in a Google search but in this case I don't find anything.
