### ISSUE TITLE
Document toolchain versioning scheme

### ISSUE THREAD

**Issue by gribozavr** [easybuilders/easybuild#9]
Current toolchain versioning scheme is a bit ad-hoc in general, but it is consistently followed in all toolchains.  It would be nice to have it documented in the wiki because it is not obvious.

**Comment by migueldiascosta** [comment]
both the <year>{a,b} versioning scheme for common toolchains and the <year>.<month> for the other versions are documented at https://easybuild.readthedocs.io/en/latest/Common-toolchains.html#versioning-scheme-for-common-toolchains
