### ISSUE TITLE
how to the system toolchain with Prefix 

### ISSUE THREAD

**Issue by dobbi84** [easybuilders/easybuild#908]
i am trying to reproduce the EESSI approach thus building using Easybuild and Gentoo Prefix. If i try to build, fo example `XZ-5.4.5-GCCcore-13.3.0`, it fails with the following error message:
```
ERROR: Build of /home/dobbi/intel/sapphirerapids/usr/easybuild/easyconfigs/g/gettext/gettext-0.22.5.eb failed (err: 'build failed (first 300 chars): cmd "/home/dobbi/intel/sapphirerapids/sources/generic/eb_v4.9.4/ConfigureMake/config.guess" exited with exit code 1 and output:\n/bin/bash: /lib64/libc.so.6: version `GLIBC_2.33\' not found (required by /home/dobbi/intel/sapphirerapids/software/ncurses/6.4/lib/libtinfo.so.6)\n')
``` 
So it is going for the system `/lib64/libc.so.6` (v2.28) instead of `lib64/libc.so.6` (v2.39) provided by Prefix.
What would be the best approach to use the Prefix provided utils and libs?

**Comment by ocaisa** [comment]
Note that `gettext` appears in `EASYBUILD_FILTER_DEPS`

**Comment by dobbi84** [comment]
Thanks i guess you provided me with the answer by mentioning `EASYBUILD_FILTER_DEPS`. I think `EASYBUILD_SYSROOT` might also be solving the issue. I will try them out.

I was trying to understand EESSI and i missed `EESSI-extend`, this explains many things.
